const BUSINESS_KEY='skinator-business-v1';
const outreachSeedText=`Pato Horneado|https://www.youtube.com/@PatoHorneado/videos|12m|pato@ageworld-agency.com|Argentine gamer|YES|
alanzoka|https://www.youtube.com/@alanzoka|9M||Slay the Spire 2 player.|YES|
The Spiffing Brit|https://www.youtube.com/@thespiffingbrit|4.5M|thespiffingbusiness@gmail.com|Slay the Spire 2 player.|YES|
zLeandro||4m|WhatsApp — account may have been hacked|Argentine YouTuber|YES|2026-05-22
robleisjaja|https://www.youtube.com/@RobleisJAJA|3.6m|robleisiutu@gmail.com|Argentine gamer|YES|
HandOfBlood|https://www.youtube.com/@HandOfBlood/videos|2.94M|HandOfBlood@instinct3.de|Variety player|YES|
Northernlion|https://www.youtube.com/@Northernlion|1.3m|northernlionbusiness@gmail.com|Slay the Spire 2 player.|YES|
Force Gaming|https://www.youtube.com/@ForceGamingYT|1m|forcegaming@peaspod.gg|Slay the Spire 2 player.|YES|
jota.|https://www.youtube.com/@Jota.|2.2m|contactojota17@gmail.com|Argentine gamer|YES|
Mr fruit|https://www.youtube.com/@Mr_Fruit/videos|2.1m|mrfruitbusiness@gmail.com|Variety player|YES|
juja|https://www.youtube.com/@jujalag/videos|806K|jujalag@gmail.com|Variety player Spain|YES|
Pravus|https://www.youtube.com/@PravusGaming/videos|671K|pravuslegacy@gmail.com|Variety indie player|YES|
2kliksphilip|https://www.youtube.com/@2kliksphilip|622k|3kliksphilip@gmail.com|Slay the Spire 2 player.|YES|
MythyMoo|https://www.youtube.com/@MythyMoo|639k|theofficialmyth@hotmail.com|Slay the Spire 2 player.|YES|
Wanderbots|https://www.youtube.com/@wanderbots/videos|520K|wanderbots@gmail.com|Variety player|YES|
theprophetyt|https://www.youtube.com/@TheProphetyt|500k|elprofetayoutube@hotmail.com|Argentine gamer|YES|
Mortismal Gaming|https://www.youtube.com/@MortismalGaming|471k|Techpunksystems@outlook.com|Slay the Spire 2 player.|YES|
lokonazo1|https://www.youtube.com/user/lokonazo1|350k|lokonazo1@hotmail.com|Argentine gamer|YES|
Rarran|https://www.youtube.com/@Rarran|312K|rarran@fixated.com|Deckbuilder player|YES|
EduCapmpsYT|https://www.youtube.com/@EduCampsYT|300K|soyeducamps@gmail.com|Argentine YouTuber|YES|2026-05-21
ambiguousamphibian VODs|https://www.youtube.com/@ambiguousamphibianvods/videos|263K|ambiguousamphibian@gmail.com|Variety roguelike player|YES|
Olexa|https://youtube.com/@OlexaYT/videos?sttick=0|232k|olexakid@gmail.com|Reviews mostly roguelikes and tower defense|YES|
Haelian|https://www.youtube.com/@Haelian|210K|haelianplays@gmail.com|He Is Coming player|YES|
Scyushi|https://www.youtube.com/@Scyushi|206K|scytheplays@gmail.com|Variety player|YES|
Olexa|https://www.youtube.com/@OlexaYT|200K|olexakid@gmail.com|Plays all sorts of roguelikes|YES|
Idle cub|https://www.youtube.com/@idlecub|151K|idlecub@gmail.com|Played TNM before|YES|
rndThursday|https://www.youtube.com/@rndThursday/videos|150K|rnd@expansion.gg|Roguelike player|YES|
Shisheyu|https://www.youtube.com/@Shisheyu|72K|shisheyu@20ty.gg|French variety player|YES|
eggstew|https://www.youtube.com/@eggstew/videos|58.7k|eggsoup@mythictalent.com|Indie player|YES|
The Singleplayer Squad|https://www.youtube.com/@thesingleplayersquad|54.1K|singleplayersquad.social@gmail.com|He Is Coming player|YES|
UHART|https://www.youtube.com/@UH4RT/videos|35.6K|Contact through Discord|Argentine let's player|YES|2026-05-20
Kurindie|https://www.youtube.com/@kurindie/videos|35.4k|contato.kurindie@gmail.com|Variety player PT|YES|
OHRye||21.6k|OHRyePlays@gmail.com|Roguelike player|YES|
Burr|https://www.youtube.com/@Burr_|25k|burr@headshot-media.com|Slay the Spire 2 player.|YES|
ELMOP|https://www.youtube.com/@elmopsito|22K|Contacto.Elmop@gmail.com|LATAM let's player|YES|2026-05-21
Indie Game Joe|https://www.youtube.com/@indiegamejoe/shorts|21.8K|info@indiegamejoe.com|Indie game reviewer|YES|2026-05-21
HarryUP|https://www.youtube.com/@HarryUpOk/videos|20K|harryalexok@gmail.com|Argentine gamer|YES|2026-05-21
MrGbx|https://www.youtube.com/@Mr-Gbx|17k|gameboxai.yt@gmail.com|Mobile player — contact later|YES|
BH Indie Gaming|https://www.youtube.com/@BH_Indie_Gaming|17K|blackhestergaming@gmail.com|Played TNM before|YES|2026-05-20
GothicLordUK|https://www.youtube.com/@GothicLordUK|16.7K|gothiclorduk@gmail.com|He Is Coming player|YES|2026-05-15
Matzel|https://www.youtube.com/@Matzelele|8.7K|matzelele.yt@gmail.com|He Is Coming player|YES|2026-05-15
BobtheGuy|https://www.youtube.com/results?search_query=BobtheGuy|8K|bobtheguy876@gmail.com|Slay the Spire player|YES|2026-05-20
리키리킹|https://www.youtube.com/@ksyliki|7.7k|lunarkittys@naver.com|Played TNM before|YES|2026-05-20
MicBeMac Games|https://www.youtube.com/@Micbemac|6.5k|micbemacgames@gmail.com|Played TNM before|YES|2026-05-20
luckynumchris|https://www.youtube.com/@luckynumchris|5.7k|Reddit message|Offered to make a video about the game|YES|2026-05-16
EL GAMER ARGENTINO|https://www.youtube.com/@elgamerargentino3000/videos|3.7k|Contact on mobile|Played TNM before|YES|2026-05-16
Mira's Hell|https://www.youtube.com/@mirahell|2.6K|kanelliscosti@gmail.com|Slay the Spire player|YES|2026-05-15
ITIZWIZ|https://www.youtube.com/@Itizwiz|1.5k|tossed.out.pro@gmail.com|Played TNM before|YES|2026-05-20
Coach Plague|https://www.youtube.com/@coachplague|1.2K|coachplagueyt@gmail.com|Roguelike player|YES|2026-05-20
Dr Pixel|https://www.youtube.com/@DrPix3l|700||Personal friend|YES|2026-05-21
ELCuk|https://www.youtube.com/@ELCuk_YT|200|elcukyt@gmail.com|Argentine gamer|YES|2026-05-21`;
const outreachSeed=outreachSeedText.split('\n').map((line,index)=>{const [name,channel,followers,email,relevancy,sent,date]=line.split('|');return{id:`outreach-seed-${index+1}`,name,channel,followers,email,relevancy,country:'',bestDay:'',bestTime:'',socialLink:channel,replied:false,reply:'',emailSent:sent==='YES',contactDate:date||''}});
const ideaCategories=['General Ideas','God Modifier Ideas','Support Modifier Ideas','Attack Modifier Ideas','Node Ideas','Quest Ideas','Companion Ideas','Map Ideas','NPC Ideas','LVL 3'];
const ideaSeedData={
'General Ideas':[
['Parts sets','Instead of limiting modifiers an enemy can have, multiple parts from the same enemy grant escalating set bonuses. Show the full set information on the swap screen.'],
['Special reward combat node','High-level or four-enemy nodes can award a chest containing special rewards such as reroll-price resets, extra gold, shop discounts, healing, or cheaper fleeing.'],
['Turbocharge','Disabling enemy parts fills a persistent turbocharge bar. Once full, turbocharge a part for a special effect such as instantly disabling an enemy part.'],
['Combo multiplier','Uninterrupted hit pairs build x2, x3, x4 combos. Corrupt and Lacerate can add more hits. Damage or end-of-fight gold can scale with the combo.'],
['Enemy Skinators','Enemy Skinators move one map square whenever the player moves, randomly or toward the player when visible, creating elite fights and Pac-Man-like pursuit moments.'],
['Lycanthrope','An encounter with a 50% chance to give something useful or transform into a monster and begin a fight.'],
['Test your might','Encounter an object with a fixed amount of health that must be broken in one round to receive the reward inside.'],
['Champion levels','Special levels accessible only with saved champions.'],
['Repopulate high-level map','Allow a one-time repopulation of the map with high-level enemies for players pursuing extreme builds.'],
['Condition system expansion','Conditions for player/enemy part health totals, missing and active health, modifier counts, targeting state, disabled state, God Eye effects, health-pool thresholds, limb type and side.']],
'God Modifier Ideas':[
['Arm damage slot','Gain +1 damage if an arm is placed in this slot.'],['Leg damage slot','Gain +1 damage if a leg is placed in this slot.'],['Head range slot','Gain +1 range if a head is placed in this slot.'],['Chest range slot','Gain +2 range if a chest is placed in this slot.'],['Arm speed slot','Gain +3 speed if an arm is placed in this slot.'],['Leg speed slot','Gain +3 speed if a leg is placed in this slot.'],['Head speed slot','Gain +3 speed if a head is placed in this slot.'],['Chest speed slot','Gain +3 speed if a chest is placed in this slot.'],['Leg protection slot','A leg in this slot receives no integrity damage this round.'],['Arm protection slot','An arm in this slot receives no integrity damage this round.'],['Head protection slot','A head in this slot receives no integrity damage this round.'],['Chest protection slot','A chest in this slot receives no integrity damage this round.'],['Dead-part healing slot','A dead part in this slot heals the parts above and below by 1.'],['Dead-part speed slot','A dead part in this slot gives the parts above and below +2 speed.'],['Greater Decay','Decay dealing 2 damage instead of 1.'],['Apex Decay','Decay dealing 3 damage instead of 2.'],['Applied attack modifiers','Modifiers that attacking parts can apply, such as poison.'],['Target lock','God Eye modifier that prevents targeting.'],['Hidden intent','Modifier that prevents seeing enemy intent.']],
'Support Modifier Ideas':[
['Arm power aura','If an arm is in range, it gains +1 damage.'],['Leg power aura','If a leg is in range, its base power is doubled.'],['Arm speed aura','If an arm is in range, its base speed is doubled.'],['Leg speed aura','If a leg is in range, its base speed is doubled.'],['Propulsion','Parts in range gain +1 speed for each active part above them.'],['Resonance','Parts in range gain +1 integrity for each active part above them.'],['Disabled speed','Parts in range gain +3 speed for each disabled part above them.'],['Disabled power','Parts in range gain +5 power for each disabled part above them.'],['Confidence','Parts in range gain 1 extra speed for each current integrity point they have.'],['Calling','Dead parts in range contribute 2 speed.'],['Character health modifiers','Support effects related to character health.'],['Modifier-count effect','Effect strength based on the number of modifiers.'],['Dead-part shielding','Shields damage on dead parts.']],
'Attack Modifier Ideas':[
['Character-health damage','Damage or effect related to character health.'],['Support sniper','Deal 3 integrity damage to any support part.'],['Damage from parts above','Deal 1 damage per part above the target.'],['Damage from parts below','Deal 1 damage per part below the target.'],['Chain','Lacerate travels both up and down, rewarding placement in the middle.'],['Bomb','Place a bomb on a part, then activate it by attacking that part again.'],['Z3','Curse variant that removes attack modifiers.']],
'Node Ideas':[],
'Quest Ideas':[
['Enemy hunter','Defeat X of a particular enemy.'],['Limb harvest','Harvest X of a particular limb.'],['Roulette prize','Get X of a particular roulette prize.'],['Shop purchases','Purchase X items from the shop.'],['Monk rests','Rest at the Wandering Monk X times.'],['Monk earnings','Make X money from the Wandering Monk.'],['Corpse roulette losses','Lose X times on the corpse-pile roulette.'],['Buy out shop','Purchase every item from the shopkeeper in one visit.'],['Monk card games','Play the Wandering Monk card game X times.'],['Card collection','Get every card except the crow in one Wandering Monk play.']],
'Companion Ideas':[],
'Map Ideas':[
['Pre-designed chunks','Create pre-designed chunks with deliberately placed decorations and events: long bridges, decorative NPCs, toll bridges, distinctive tiles, destructible rocks and roadblocks requiring enough damage.'],['Reactive particles','Birds fly away as the player passes, creatures bury themselves, and small bugs scatter.']],
'NPC Ideas':[
['Coin toss NPC','Choose a bet of 200, 1000, or 50% of current gold. A 50% chance doubles it and a 50% chance loses it.'],['Memory game NPC','Twenty freezers or bags. The player gets three attempts to find matching pairs and wins the matching reward.'],['Necromancer','Creates high-level enemies to recover or intensify a weak run.'],['Heart Editor','Shows modifier and position options for the heart.'],['Lycanthrope','A person with a 50% chance to transform into a wolf and fight or give a reward.']],
'LVL 3':[
['Bullet-based arms','Characters with bullet-based arm attacks.'],['Attacking heads','Head attacks instead of support behavior.'],['Delayed modifiers','Placed modifiers that activate on a second hit.']]
};
const ideaSeed=Object.entries(ideaSeedData).flatMap(([category,items])=>items.map(([title,description],index)=>({id:`idea-${category.toLowerCase().replace(/\W/g,'-')}-${index+1}`,category,title,description})));
const businessSaved=(()=>{try{return JSON.parse(localStorage.getItem(BUSINESS_KEY))}catch{return null}})();
let outreachRecords=businessSaved?.outreach||outreachSeed,publisherRecords=businessSaved?.publishers||[],ideaRecords=businessSaved?.ideas||ideaSeed,businessEditing=null,businessIdeaCategory='General Ideas';
const saveBusiness=()=>{localStorage.setItem(BUSINESS_KEY,JSON.stringify({outreach:outreachRecords,publishers:publisherRecords,ideas:ideaRecords}));window.skinatorCloudSave?.()};

document.querySelector('aside nav').insertAdjacentHTML('beforeend','<button class="nav" data-tab="outreach"><i>◎</i> OUTREACH <span id="navOutreachCount">0</span></button><button class="nav" data-tab="publishers"><i>◆</i> PUBLISHERS <span id="navPublisherCount">0</span></button><button class="nav" data-tab="ideas"><i>✧</i> IDEAS <span id="navIdeaCount">0</span></button>');
document.querySelector('main').insertAdjacentHTML('beforeend',`<section id="outreachView" class="business-view" hidden><section class="panel"><div class="toolbar"><label class="search">⌕ <input id="outreachSearch" placeholder="SEARCH CREATORS"></label><select id="outreachReplyFilter" class="toolbar-select"><option value="All">ALL REPLIES</option><option value="Replied">REPLIED</option><option value="Waiting">WAITING</option></select><span id="outreachResultCount"></span></div><div id="outreachGrid" class="business-grid"></div></section></section><section id="publishersView" class="business-view" hidden><section class="panel"><div class="toolbar"><label class="search">⌕ <input id="publisherSearch" placeholder="SEARCH PUBLISHERS"></label><span id="publisherResultCount"></span></div><div id="publisherGrid" class="business-grid"></div></section></section><section id="ideasView" class="business-view" hidden><section class="panel ideas-layout"><aside id="ideaCategories" class="idea-categories"></aside><div><div class="toolbar"><label class="search">⌕ <input id="ideaSearch" placeholder="SEARCH IDEAS"></label><span id="ideaResultCount"></span></div><div id="ideaGrid" class="business-grid"></div></div></section></section>`);
document.body.insertAdjacentHTML('beforeend',`<dialog id="businessDialog" class="business-dialog"><form id="businessForm"><div class="dialog-head"><div><p id="businessDialogType">DATABASE</p><h2 id="businessDialogTitle">New record</h2></div><button type="button" class="x" id="businessClose">×</button></div><div class="dialog-body business-editor" id="businessFields"></div><div class="dialog-actions"><button type="button" class="btn danger" id="businessDelete">DELETE</button><span></span><button type="button" class="btn ghost" id="businessCancel">CANCEL</button><button class="btn red" type="submit">SAVE</button></div></form></dialog>`);
const businessField=(label,id,value='',type='text')=>`<label>${label}<input id="${id}" type="${type}" value="${escapeHtml(value)}"></label>`;
function renderOutreach(){const q=($('outreachSearch').value||'').toLowerCase(),filter=$('outreachReplyFilter').value,rows=outreachRecords.filter(r=>`${r.name} ${r.channel} ${r.email} ${r.relevancy} ${r.country}`.toLowerCase().includes(q)&&(filter==='All'||(filter==='Replied')===!!r.replied));$('navOutreachCount').textContent=outreachRecords.length;$('outreachResultCount').textContent=plural(rows.length,'CONTACT');$('outreachGrid').innerHTML=rows.map(r=>`<article class="contact-card" data-business="outreach" data-id="${r.id}"><span class="contact-type">CREATOR // ${escapeHtml(r.country||'COUNTRY TBD')}</span><span class="reply-pill ${r.replied?'yes':''}">${r.replied?'REPLIED':'WAITING'}</span><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.relevancy||'No relevance notes yet.')}</p><div class="contact-meta"><span>${escapeHtml(r.followers||'—')} FOLLOWERS</span><span>${r.emailSent?'EMAIL SENT':'NOT SENT'}</span>${r.contactDate?`<span>${escapeHtml(r.contactDate)}</span>`:''}</div><div class="contact-links">${r.channel?`<a href="${escapeHtml(r.channel)}" target="_blank" rel="noopener">${escapeHtml(r.channel)}</a>`:''}${r.email?`<a href="mailto:${escapeHtml(r.email)}">${escapeHtml(r.email)}</a>`:''}</div></article>`).join('')||'<div class="business-empty">NO CONTACTS MATCH THIS FILTER</div>';bindBusinessCards()}
function renderPublishers(){const q=($('publisherSearch').value||'').toLowerCase(),rows=publisherRecords.filter(r=>`${r.name} ${r.email} ${r.gameTypes} ${r.platform}`.toLowerCase().includes(q));$('navPublisherCount').textContent=publisherRecords.length;$('publisherResultCount').textContent=plural(rows.length,'PUBLISHER');$('publisherGrid').innerHTML=rows.map(r=>`<article class="contact-card" data-business="publisher" data-id="${r.id}"><span class="contact-type">PUBLISHER // ${escapeHtml(r.platform||'PLATFORM TBD')}</span><span class="reply-pill ${r.replied?'yes':''}">${r.replied?'REPLIED':'WAITING'}</span><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.gameTypes||'No publishing focus entered.')}</p><div class="contact-links">${r.website?`<a href="${escapeHtml(r.website)}" target="_blank" rel="noopener">${escapeHtml(r.website)}</a>`:''}${r.email?`<a href="mailto:${escapeHtml(r.email)}">${escapeHtml(r.email)}</a>`:''}</div></article>`).join('')||'<div class="business-empty">NO PUBLISHERS YET</div>';bindBusinessCards()}
function renderIdeas(){const q=($('ideaSearch').value||'').toLowerCase(),rows=ideaRecords.filter(r=>r.category===businessIdeaCategory&&`${r.title} ${r.description}`.toLowerCase().includes(q));$('navIdeaCount').textContent=ideaRecords.length;$('ideaCategories').innerHTML=ideaCategories.map(c=>`<button class="idea-category-btn ${c===businessIdeaCategory?'active':''}" data-category="${escapeHtml(c)}">${escapeHtml(c)} <span>${ideaRecords.filter(i=>i.category===c).length}</span></button>`).join('');$('ideaResultCount').textContent=plural(rows.length,'IDEA');$('ideaGrid').innerHTML=rows.map(r=>`<article class="idea-card" data-business="idea" data-id="${r.id}"><span class="idea-category">${escapeHtml(r.category)}</span><h3>${escapeHtml(r.title||'UNTITLED IDEA')}</h3><p>${escapeHtml(r.description)}</p></article>`).join('')||'<div class="business-empty">NO IDEAS IN THIS CATEGORY YET</div>';$('ideaCategories').querySelectorAll('button').forEach(b=>b.onclick=()=>{businessIdeaCategory=b.dataset.category;renderIdeas()});bindBusinessCards()}
function bindBusinessCards(){document.querySelectorAll('[data-business][data-id]').forEach(card=>card.onclick=e=>{if(e.target.closest('a'))return;openBusiness(card.dataset.business,card.dataset.id)})}
function openBusiness(type,id=null){businessEditing={type,id};const list=type==='outreach'?outreachRecords:type==='publisher'?publisherRecords:ideaRecords,record=list.find(r=>r.id===id)||{};$('businessDialogType').textContent=type.toUpperCase()+' DATABASE';$('businessDialogTitle').textContent=id?'Edit record':'New record';$('businessDelete').hidden=!id;if(type==='outreach')$('businessFields').innerHTML=`<div class="three">${businessField('NAME *','bizName',record.name)}${businessField('FOLLOWERS','bizFollowers',record.followers)}${businessField('COUNTRY','bizCountry',record.country)}</div><div class="two">${businessField('CONTACT EMAIL / METHOD','bizEmail',record.email)}${businessField('CHANNEL LINK','bizChannel',record.channel,'url')}</div><label>RELEVANCY FOR SKINATOR<textarea id="bizDescription" rows="4">${escapeHtml(record.relevancy||'')}</textarea></label><div class="three">${businessField('BEST DAY TO CONTACT','bizDay',record.bestDay)}${businessField('BEST TIME','bizTime',record.bestTime)}${businessField('CONTACT DATE','bizDate',record.contactDate,'date')}</div>${businessField('OTHER SOCIAL MEDIA LINK','bizSocial',record.socialLink,'url')}<div class="two"><label><span>OUTREACH STATUS</span><span class="check-row"><input id="bizSent" type="checkbox" ${record.emailSent?'checked':''}> EMAIL SENT</span></label><label><span>REPLY STATUS</span><span class="check-row"><input id="bizReplied" type="checkbox" ${record.replied?'checked':''}> THEY REPLIED</span></label></div><label>WHAT THEY SAID<textarea id="bizReply" rows="4">${escapeHtml(record.reply||'')}</textarea></label>`;else if(type==='publisher')$('businessFields').innerHTML=`<div class="two">${businessField('PUBLISHER NAME *','bizName',record.name)}${businessField('PLATFORM','bizPlatform',record.platform)}</div><div class="two">${businessField('CONTACT EMAIL','bizEmail',record.email,'email')}${businessField('WEBSITE','bizWebsite',record.website,'url')}</div><label>HOW TO CONTACT<textarea id="bizContact" rows="3">${escapeHtml(record.contactMethod||'')}</textarea></label><label>TYPE OF GAMES THEY PUBLISH<textarea id="bizDescription" rows="4">${escapeHtml(record.gameTypes||'')}</textarea></label><label><span>REPLY STATUS</span><span class="check-row"><input id="bizReplied" type="checkbox" ${record.replied?'checked':''}> THEY REPLIED</span></label><label>WHAT THEY SAID<textarea id="bizReply" rows="4">${escapeHtml(record.reply||'')}</textarea></label>`;else $('businessFields').innerHTML=`<label>CATEGORY<select id="bizCategory">${ideaCategories.map(c=>`<option ${c===(record.category||businessIdeaCategory)?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select></label>${businessField('IDEA TITLE *','bizName',record.title)}<label>SHORT DESCRIPTION<textarea id="bizDescription" rows="8">${escapeHtml(record.description||'')}</textarea></label>`;$('businessDialog').showModal()}
function renderBusiness(){renderOutreach();renderPublishers();renderIdeas()}
$('businessForm').onsubmit=e=>{e.preventDefault();const {type,id}=businessEditing,record={id:id||crypto.randomUUID()};if(type==='outreach'){Object.assign(record,{name:$('bizName').value.trim(),followers:$('bizFollowers').value.trim(),country:$('bizCountry').value.trim(),email:$('bizEmail').value.trim(),channel:$('bizChannel').value.trim(),relevancy:$('bizDescription').value.trim(),bestDay:$('bizDay').value.trim(),bestTime:$('bizTime').value.trim(),contactDate:$('bizDate').value,socialLink:$('bizSocial').value.trim(),emailSent:$('bizSent').checked,replied:$('bizReplied').checked,reply:$('bizReply').value.trim()});outreachRecords=id?outreachRecords.map(r=>r.id===id?record:r):[record,...outreachRecords]}else if(type==='publisher'){Object.assign(record,{name:$('bizName').value.trim(),platform:$('bizPlatform').value.trim(),email:$('bizEmail').value.trim(),website:$('bizWebsite').value.trim(),contactMethod:$('bizContact').value.trim(),gameTypes:$('bizDescription').value.trim(),replied:$('bizReplied').checked,reply:$('bizReply').value.trim()});publisherRecords=id?publisherRecords.map(r=>r.id===id?record:r):[record,...publisherRecords]}else{Object.assign(record,{category:$('bizCategory').value,title:$('bizName').value.trim(),description:$('bizDescription').value.trim()});ideaRecords=id?ideaRecords.map(r=>r.id===id?record:r):[record,...ideaRecords];businessIdeaCategory=record.category}saveBusiness();renderBusiness();$('businessDialog').close();toast('SHARED RECORD SAVED')};
$('businessDelete').onclick=()=>{const {type,id}=businessEditing;if(!confirm('Delete this record?'))return;if(type==='outreach')outreachRecords=outreachRecords.filter(r=>r.id!==id);else if(type==='publisher')publisherRecords=publisherRecords.filter(r=>r.id!==id);else ideaRecords=ideaRecords.filter(r=>r.id!==id);saveBusiness();renderBusiness();$('businessDialog').close();toast('RECORD DELETED')};$('businessClose').onclick=$('businessCancel').onclick=()=>$('businessDialog').close();$('outreachSearch').oninput=renderOutreach;$('outreachReplyFilter').onchange=renderOutreach;$('publisherSearch').oninput=renderPublishers;$('ideaSearch').oninput=renderIdeas;
const businessPreviousSetTab=setTab;setTab=function(tab){const businessTabs=['outreach','publishers','ideas'];document.querySelectorAll('.business-view').forEach(view=>view.hidden=view.id!==`${tab}View`);if(!businessTabs.includes(tab)){businessPreviousSetTab(tab);return}state.tab=tab;document.querySelectorAll('.nav[data-tab]').forEach(n=>n.classList.toggle('active',n.dataset.tab===tab));['charactersView','modifiersView','npcsView','trackerView','parasytesView'].forEach(id=>$(id).hidden=true);const content={outreach:['Outreach','CREATOR RELATIONS','Track YouTubers, streamers, contact timing and replies.','＋ NEW CONTACT'],publishers:['Publishers','PUBLISHER RELATIONS','Track publishing partners, platforms, fit and conversations.','＋ NEW PUBLISHER'],ideas:['Ideas Bank','DESIGN ARCHIVE','Capture and browse game ideas by category.','＋ NEW IDEA']}[tab];$('pageTitle').textContent=content[0];$('breadcrumb').textContent=content[1];$('pageSubtitle').textContent=content[2];$('createBtn').hidden=false;$('createBtn').textContent=content[3];$('createBtn').onclick=()=>openBusiness(tab==='publishers'?'publisher':tab==='ideas'?'idea':'outreach');renderBusiness()};
['outreach','publishers','ideas'].forEach(tab=>document.querySelector(`.nav[data-tab="${tab}"]`).onclick=()=>setTab(tab));renderBusiness();
