const INFLUENCER_VIDEO_FIELDS=[
  {
    "key": "tutorialClarity",
    "label": "Tutorial clarity",
    "group": "scores"
  },
  {
    "key": "combatUnderstanding",
    "label": "Combat understanding",
    "group": "scores"
  },
  {
    "key": "modifierUnderstanding",
    "label": "Modifier understanding",
    "group": "scores"
  },
  {
    "key": "lootExcitement",
    "label": "Loot excitement",
    "group": "scores"
  },
  {
    "key": "strategicDepthPerceived",
    "label": "Strategic depth perceived",
    "group": "scores"
  },
  {
    "key": "overallEnjoyment",
    "label": "Overall enjoyment",
    "group": "scores"
  },
  {
    "key": "replayIntent",
    "label": "Replay intent",
    "group": "scores"
  },
  {
    "key": "totalFights",
    "label": "Total fights",
    "group": "session"
  },
  {
    "key": "saysGameIsFun",
    "label": "Says game is fun",
    "group": "session"
  },
  {
    "key": "saysWouldPlayAgain",
    "label": "Says they would play again",
    "group": "session"
  },
  {
    "key": "startsTutorial",
    "label": "Starts tutorial",
    "group": "timeline"
  },
  {
    "key": "finishesTutorial",
    "label": "Finishes tutorial",
    "group": "timeline"
  },
  {
    "key": "tutorialDuration",
    "label": "Tutorial duration",
    "group": "timeline"
  },
  {
    "key": "firstCombatAfterTutorial",
    "label": "First combat after tutorial",
    "group": "timeline"
  },
  {
    "key": "firstPartAcquired",
    "label": "First part acquired",
    "group": "timeline"
  },
  {
    "key": "firstShopEncounter",
    "label": "First shop encounter",
    "group": "timeline"
  },
  {
    "key": "monkDies",
    "label": "Monk dies?",
    "group": "timeline"
  },
  {
    "key": "oborogumoEncounter",
    "label": "Oborogumo encounter",
    "group": "timeline"
  },
  {
    "key": "templePriestEncounter",
    "label": "Temple priest encounter",
    "group": "timeline"
  },
  {
    "key": "finalBossEncounter",
    "label": "Final boss encounter",
    "group": "timeline"
  },
  {
    "key": "wanderingMonkEncounter",
    "label": "Wandering Monk encounter",
    "group": "timeline"
  },
  {
    "key": "firstPotionEncounter",
    "label": "First potion encounter",
    "group": "timeline"
  },
  {
    "key": "firstUnderstandingMoment",
    "label": "First understanding moment",
    "group": "timeline"
  },
  {
    "key": "firstExcitementSpike",
    "label": "First excitement spike",
    "group": "timeline"
  },
  {
    "key": "firstCriticism",
    "label": "First criticism",
    "group": "timeline"
  },
  {
    "key": "firstGameIsEasyComment",
    "label": "First \"game is easy\" comment",
    "group": "timeline"
  },
  {
    "key": "firstLootChosen",
    "label": "First loot chosen",
    "group": "timeline"
  },
  {
    "key": "firstBuildModification",
    "label": "First build modification",
    "group": "timeline"
  },
  {
    "key": "firstConfusionEvent",
    "label": "First confusion event",
    "group": "timeline"
  },
  {
    "key": "firstStrategicInsight",
    "label": "First strategic insight",
    "group": "timeline"
  },
  {
    "key": "videoEnds",
    "label": "Video ends",
    "group": "timeline"
  },
  {
    "key": "firstCorpseMongerEncounter",
    "label": "First corpse monger encounter",
    "group": "timeline"
  },
  {
    "key": "playsSecondRound",
    "label": "Plays a second round",
    "group": "session"
  }
];
const INFLUENCER_ANALYSIS_SEED={
  "creators": [
    {
      "id": "influencer-captaincapybara",
      "name": "CaptainCapybara",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-we-playtest-games",
      "name": "We Playtest Games",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-hexy-arts",
      "name": "Hexy Arts",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-fort-kenmei",
      "name": "Fort Kenmei",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-twicefry",
      "name": "Twicefry",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-druid",
      "name": "Druid",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-draculdaculdrac",
      "name": "DraculDaculDRAC",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-foshoshot",
      "name": "FoShoShot",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-miro-mcrain",
      "name": "Miro McRain",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-moistcr1tikal-gaming",
      "name": "MoistCr1TiKaL Gaming",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-angel11155",
      "name": "Angel11155",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-squidlord-xd",
      "name": "SquidLord XD",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-shadow-freddy",
      "name": "Shadow Freddy",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-karab-nn-play",
      "name": "Karabеnn-Play",
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    }
  ],
  "videos": [
    {
      "id": "influencer-video-captaincapybara-2026-05-19-1",
      "creatorId": "influencer-captaincapybara",
      "date": "2026-05-19",
      "subscribers": "196",
      "views": "3",
      "videoLink": "https://www.youtube.com/watch?v=u-ouAopVi1s",
      "values": {
        "tutorialClarity": "9",
        "combatUnderstanding": "9",
        "modifierUnderstanding": "8",
        "lootExcitement": "8",
        "strategicDepthPerceived": "8",
        "overallEnjoyment": "8",
        "replayIntent": "8",
        "totalFights": "15+",
        "saysGameIsFun": "Yes",
        "saysWouldPlayAgain": "Implicit Yes",
        "startsTutorial": "1:08",
        "finishesTutorial": "~06:20",
        "tutorialDuration": "~05:10",
        "firstCombatAfterTutorial": "~07:00",
        "firstPartAcquired": "~09:10",
        "firstShopEncounter": "~19:30",
        "monkDies": "No",
        "oborogumoEncounter": "No",
        "templePriestEncounter": "~32:00",
        "finalBossEncounter": "No",
        "wanderingMonkEncounter": "~23:30",
        "firstPotionEncounter": "~22:00",
        "firstUnderstandingMoment": "1:40",
        "firstExcitementSpike": "0:45",
        "firstCriticism": "None",
        "firstGameIsEasyComment": "2:20",
        "firstLootChosen": "9:10",
        "firstBuildModification": "3:20",
        "firstConfusionEvent": "3:40",
        "firstStrategicInsight": "2:20",
        "videoEnds": "~46:00",
        "firstCorpseMongerEncounter": "~28:40"
      },
      "notes": {
        "overall": "The creator immediately connected with SKINATOR's concept, presentation, and atmosphere. They picked up the core mechanics quickly and spent most of the playthrough experimenting with builds, modifiers, and targeting decisions. Unlike some creators who focused heavily on critique, this player approached the game with enthusiasm and curiosity, frequently verbalizing their thought process while learning. The run eventually ended in defeat, but the creator treated the loss as a learning experience and remained highly positive about the game.",
        "positive": "The creator frequently praised the game's visuals, music, and overall concept. They appeared particularly excited by the idea of defeating enemies and taking their body parts to strengthen their build. They enjoyed inspecting modifiers, comparing upgrades, and planning combat decisions. Throughout the video they repeatedly expressed that they were enjoying themselves and described the game as fun multiple times. Even after losing their run, they encouraged viewers to check the game out and wishlist it.",
        "negative": "The creator experienced some early confusion while learning the tutorial and occasionally misunderstood how turn order or certain mechanics worked. Most confusion was short-lived and resolved through experimentation or reading tooltips. The only major mistake occurred near the end of the run when they failed to inspect an enemy syringe modifier, which ultimately contributed to their defeat. They acknowledged this themselves and did not blame the game for the loss.",
        "directFeedback": "The creator repeatedly commented that they liked the game's atmosphere, music, and overall premise. They quickly grasped the core loop and enjoyed the process of improving their build through stolen body parts. Their strongest gameplay feedback came near the end of the run when they realized an enemy syringe modifier was refilling the opponent's health pool, a mechanic they had overlooked. Despite losing, they described the game as \"very fun,\" encouraged viewers to play it, and recommended wishlisting it on Steam."
      },
      "createdAt": "2026-05-19T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-we-playtest-games-2026-05-19-1",
      "creatorId": "influencer-we-playtest-games",
      "date": "2026-05-19",
      "subscribers": "384",
      "views": "23",
      "videoLink": "https://www.youtube.com/watch?v=Tb5wVUJw7xI&t=5s",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator approached SKINATOR as a thoughtful strategy game and spent a large portion of the video trying to understand the interactions between body parts, modifiers, speed, and targeting. Rather than rushing through encounters, they frequently paused to inspect mechanics and reason through decisions. By the end of the playthrough they had developed a strong understanding of the game's systems and spent several minutes reflecting on the design, progression, and tactical depth.",
        "positive": "The creator enjoyed discovering how different modifiers and body parts interacted and frequently commented on the depth of the combat system. They appreciated that random modifiers changed their plans from fight to fight and felt that the game encouraged adaptation rather than repeating the same solution every encounter. By the end of the video they described the game as fun, praised the variety created by modifiers, and stated that they did not encounter any major issues during the playtest.",
        "negative": "The creator struggled with some aspects of the tutorial and felt that information was introduced in an unusual order. Several mechanics required experimentation before becoming fully clear, particularly during the early tutorial sections. They felt the tutorial occasionally explained concepts after the player had already encountered situations where that information would have been useful. However, these concerns diminished as they became more familiar with the systems.",
        "directFeedback": "The creator's strongest feedback focused on the tutorial structure. They felt the tutorial was thorough but sometimes introduced information later than expected. At the same time, they praised the in-game question mark help system and described it as extremely useful for understanding mechanics. Their final impression was very positive, stating that the game was complex in a good way, that random modifiers kept encounters fresh, and that they did not find any significant issues during the playtest."
      },
      "createdAt": "2026-05-19T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-hexy-arts-2026-05-19-1",
      "creatorId": "influencer-hexy-arts",
      "date": "2026-05-19",
      "subscribers": "123",
      "views": "89",
      "videoLink": "https://www.youtube.com/watch?v=5DMn9k86CZI&t=2s",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator approached SKINATOR from both a player and developer perspective, frequently commenting on game design, visual feedback, UI readability, and system clarity. They quickly understood the core combat loop and spent a significant portion of the playthrough experimenting with builds, modifiers, and progression systems. The player remained engaged throughout a long session and consistently evaluated how well different mechanics communicated information to the player.",
        "positive": "The creator responded very positively to the core concept of targeting and stealing enemy body parts. They repeatedly praised the visual feedback, UI responsiveness, animations, sound design, and overall level of polish. Several times they commented on how well information was communicated visually and specifically highlighted the real-time modifier previews and targeting feedback as good design decisions. By the end of the video they described the game as original, well designed, and easy to recommend.",
        "negative": "The creator experienced occasional confusion while learning the tutorial and understanding some of the deeper mechanics. Most of these moments were related to discovering systems rather than frustration with the design itself. The only significant negative feedback came at the end of the playthrough when a bug prevented them from continuing normally and effectively forced the session to end. Outside of that issue, they appeared satisfied with the experience.",
        "directFeedback": "The creator repeatedly emphasized the importance of visual feedback and complimented several interface decisions that helped communicate game mechanics. They specifically praised the highlighting of affected parts, the real-time updating of values, and the visual indicators used during combat. At the end of the video they stated that the game \"plays really well\" and \"looks good,\" and said they would recommend it. Their strongest criticism was directed at the bug encountered near the end of the run, which interrupted gameplay and became the final talking point of the video."
      },
      "createdAt": "2026-05-19T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-fort-kenmei-2026-05-23-1",
      "creatorId": "influencer-fort-kenmei",
      "date": "2026-05-23",
      "subscribers": "681",
      "views": "83",
      "videoLink": "https://www.youtube.com/watch?v=J5lLwrMcnPY",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator approached SKINATOR from a reviewer perspective rather than a competitive or optimization perspective. They spent a significant amount of time evaluating the game's presentation, readability, tutorial flow, and overall player experience. While they occasionally struggled to follow everything happening on screen, they consistently engaged with the mechanics and attempted to understand how the systems worked. By the end of the video they had a strong understanding of the core gameplay loop and expressed a very positive overall opinion of the game.",
        "positive": "The creator responded very positively to the game's core concept, art style, and body-part stealing mechanic. They enjoyed discovering new modifiers, experimenting with upgrades, and watching their character grow stronger. They repeatedly praised the originality of the idea and remained engaged throughout the play session. By the end of the video they explicitly stated that they loved the game, enjoyed it greatly, and intended to continue playing after finishing the recording.",
        "negative": "The creator occasionally felt overwhelmed by the amount of information presented on screen, particularly during the tutorial and early combat encounters. Several mechanics required additional explanation before becoming clear, and they noted that new players might struggle to identify which information is most important. The overall complexity of the interface created some friction during the onboarding process. They also experienced technical issues related to loading and browser performance before starting the game.",
        "directFeedback": "The creator directly commented that the tutorial was good but that they struggled at times to keep up with the amount of information being presented. They suggested that reducing visual clutter or hiding certain interface elements until needed could make the onboarding experience easier for new players. Despite these concerns, they consistently praised the game's design, originality, and progression systems, ultimately recommending the game and expressing a desire to continue playing beyond the scope of the video."
      },
      "createdAt": "2026-05-23T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-twicefry-2026-06-02-1",
      "creatorId": "influencer-twicefry",
      "date": "2026-06-02",
      "subscribers": "2",
      "views": "4",
      "videoLink": "https://www.youtube.com/watch?v=-kfx3v0DyKk",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The player understood the core gameplay loop very quickly and had little trouble progressing through the game. Most of their frequent \"What does this do?\" comments appeared to be narration for their audience rather than genuine confusion. They regularly inspected modifiers, compared body parts, and adapted their build, but quickly settled on a simple combat strategy that remained effective throughout the entire playthrough. The player completed the tutorial, explored several progression events, acquired multiple upgrades, and finished the video with a very positive opinion of the game.",
        "positive": "The player engaged heavily with the body-part collection and upgrade systems. They frequently compared loot, expressed excitement when finding stronger parts, and showed a clear desire to improve their build. They quickly understood combat mechanics, positioning, attack order, and modifier placement. Several upgrade moments generated enthusiastic reactions, particularly when acquiring powerful attacking parts. The player remained engaged throughout the session and explicitly stated that they found the game fun and intended to continue playing in the future.",
        "negative": "The player discovered a highly effective strategy early in the run and relied on it for most encounters. As a result, they frequently described combat as simple and questioned why they would choose alternative approaches. The game provided little resistance until encountering an enemy with healing mechanics. There was also some confusion around revive timing and identifying the source of enemy healing, although these issues were eventually resolved. Outside of those moments, the player encountered few obstacles and generally felt in control of the game.",
        "directFeedback": "The player directly stated multiple times that the game felt easy and repeatedly commented that eliminating enemy attacking parts appeared to be the optimal solution. They questioned whether there was a reason to use different strategies and suggested through their gameplay that combat encounters were not forcing meaningful adaptation. At the same time, they reacted positively whenever a fight introduced unexpected complexity, particularly when enemy healing disrupted their expectations. The player ended the video by describing the game as \"really fun\" and explicitly stated that they intended to play more of it later."
      },
      "createdAt": "2026-06-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-druid-2026-06-02-1",
      "creatorId": "influencer-druid",
      "date": "2026-06-02",
      "subscribers": "12",
      "views": "27",
      "videoLink": "https://www.youtube.com/watch?v=S6fbGGsE_mg",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator was immediately attracted to SKINATOR's visual style, atmosphere, and core premise. Before even starting the tutorial, they expressed excitement about the concept of stealing enemy body parts and repeatedly praised the game's presentation. Throughout the playthrough they actively tried to understand the mechanics, engaged with build decisions, reached several progression events, and eventually lost a run. Despite the defeat, they finished with a highly positive impression of the game and spent several minutes discussing its future potential.",
        "positive": "The creator responded extremely positively to the game's art direction, music, atmosphere, and core body-part stealing mechanic. They quickly engaged with build optimization, understood positioning and modifier interactions, and appeared invested in finding stronger combinations. Even after losing their run, they remained enthusiastic and described the game as having significant potential. They specifically praised the mood created by the soundtrack and repeatedly suggested that the game could become something special with further development.",
        "negative": "The creator experienced some confusion during the tutorial and early combat encounters while learning how modifiers, positioning, and targeting interacted. Several mechanics required experimentation before becoming clear. They also struggled with a difficult late-game encounter that ultimately ended their run. However, most of the negative moments stemmed from learning the systems rather than frustration with the game itself. Unlike some other creators, they did not describe the game as easy and generally viewed challenges as part of the learning process.",
        "directFeedback": "The creator repeatedly praised the game's visuals, atmosphere, and unique premise. They described the game as looking \"really awesome\" and expressed excitement before entering gameplay. After completing the run, they stated that they were impressed and encouraged viewers to try the game themselves and provide feedback to the developers. They also commented that the game still has room to grow because it is a demo, but felt that it showed strong potential and could become \"something really cool\" or even \"awesome\" with further development. They specifically mentioned ideas such as PvP and ranked play while discussing future possibilities."
      },
      "createdAt": "2026-06-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-draculdaculdrac-2026-06-02-1",
      "creatorId": "influencer-draculdaculdrac",
      "date": "2026-06-02",
      "subscribers": "74",
      "views": "1",
      "videoLink": "https://www.youtube.com/watch?v=N_OwL-dTV68",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The player approached SKINATOR as a systems-focused strategy game rather than an action game. They spent a significant amount of time inspecting modifiers, comparing body parts, optimizing builds, and planning future upgrades. Unlike some creators who quickly settle on a single strategy, this player continuously adapted their decisions based on enemy modifiers, loot opportunities, shops, and progression events. They reached Oborogumo, the Temple Priest, and the first boss, showing a strong level of engagement with the game's long-term progression systems.",
        "positive": "The player appeared highly engaged with the buildcrafting aspects of the game. They frequently inspected modifiers, evaluated loot upgrades carefully, revisited shops, and looked for ways to improve their build. They enjoyed finding strong combinations and expressed satisfaction when their build became powerful. The player remained engaged for a long play session and showed interest in progression systems beyond simple combat encounters.",
        "negative": "The player initially found several mechanics difficult to understand and described the game as complicated during the early stages. They experienced confusion around combat sequencing, revive timing, and certain modifier interactions. Some information required repeated inspection before becoming clear. While they eventually understood most systems, the onboarding experience appeared more demanding for this player than for some other creators.",
        "directFeedback": "The player directly described the game as \"a bit complicated\" during the early experience. They frequently paused to read tooltips and verify how mechanics worked before making decisions. As the run progressed, they became increasingly focused on optimization and strategy, suggesting that the game's depth became more apparent over time. During the boss encounter they commented on the challenge level and treated the fight as a meaningful difficulty spike rather than an easy victory."
      },
      "createdAt": "2026-06-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-foshoshot-2026-06-03-1",
      "creatorId": "influencer-foshoshot",
      "date": "2026-06-03",
      "subscribers": "1.54K",
      "views": "20",
      "videoLink": "https://www.youtube.com/watch?v=xFP0UhG6oLA&t=924s",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator immediately connected with SKINATOR’s atmosphere, presentation, and core concept, but initially felt overwhelmed by the amount of information being presented. After restarting the tutorial and spending more time experimenting with the mechanics, they gradually became deeply engaged with the game’s systems. Over the course of the playthrough they became increasingly focused on buildcrafting, modifier interactions, loot optimization, and progression. By the end of the session they expressed strong enthusiasm for the game and described it as much larger and deeper than they originally expected.",
        "positive": "The creator repeatedly praised the game’s art style, music, atmosphere, and overall presentation. They became especially excited once they started discovering stronger body parts and meaningful modifier combinations. Throughout the run they actively experimented with positioning, range, support modifiers, and defensive effects while constantly evaluating upgrades. Their enthusiasm noticeably increased as the session progressed, and by the end they described the game as “very cool,” “fun,” and significantly more expansive than they initially assumed.",
        "negative": "The creator’s main struggle was onboarding complexity. Very early in the playthrough they openly admitted that even after completing the tutorial once, they still did not fully understand many of the mechanics. Several systems required experimentation before becoming clear, and they occasionally questioned why certain tutorial actions were optimal. However, these concerns diminished over time as they gained experience and became more comfortable with the game’s systems. No major complaints about balance, progression, or overall design were expressed.",
        "directFeedback": "The creator directly stated that they initially felt overwhelmed by the tutorial and did not fully understand the game after completing it the first time. Despite this, they repeatedly praised the game’s visuals, atmosphere, and music from the very beginning. As the playthrough continued, they became increasingly engaged with the buildcrafting systems and repeatedly commented on how strong or interesting specific body parts and modifiers felt. Near the end of the video they expressed surprise at the game’s scale and progression structure, stating that the game felt much bigger and deeper than they originally expected. They finished the session with strong positive sentiment and encouraged viewers to try the game themselves."
      },
      "createdAt": "2026-06-03T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-twicefry-2026-06-03-2",
      "creatorId": "influencer-twicefry",
      "date": "2026-06-03",
      "subscribers": "2",
      "views": "2",
      "videoLink": "https://www.youtube.com/watch?v=y-OEMRBtetU",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator returned for a second playthrough with a much stronger understanding of the game’s systems and immediately jumped into experimentation and optimization. Unlike the first video, they spent far less time learning mechanics and much more time evaluating loot, planning upgrades, and progressing through events. The overall tone of the playthrough was highly enthusiastic, with the creator appearing increasingly invested as the run progressed.",
        "positive": "The creator was extremely excited by new body parts, modifiers, and enemy designs throughout the video. Loot upgrades consistently generated strong reactions, especially when finding parts with healing or extra damage effects. They appeared comfortable with the combat systems and repeatedly relied on strategies involving targeting enemy attack parts first. The creator also showed clear interest in progression systems such as the Wandering Monk, shops, and Temple Priest encounters.",
        "negative": "The creator occasionally ignored or skipped reading certain modifiers and admitted they were relying on “tried and true” strategies rather than fully adapting to every encounter. While they understood the systems much better than in the previous video, they still sometimes overlooked enemy mechanics or chose not to engage deeply with positioning strategies. However, these moments appeared to come more from confidence and familiarity than confusion.",
        "directFeedback": "The creator repeatedly praised enemy designs, loot upgrades, and the satisfaction of stealing stronger body parts from enemies. They directly described several upgrades as “really good” and showed consistent excitement whenever they discovered powerful combinations. Their strongest gameplay observation was that targeting enemy attacking parts remained highly effective throughout most encounters. Compared to the first playthrough, the creator appeared far more comfortable with the game’s mechanics and progression systems and expressed clear interest in continuing to play more."
      },
      "createdAt": "2026-06-03T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-miro-mcrain-2026-06-03-1",
      "creatorId": "influencer-miro-mcrain",
      "date": "2026-06-03",
      "subscribers": "258",
      "views": "9",
      "videoLink": "https://www.youtube.com/watch?v=J6oJdbLeb-U",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator was immediately interested in SKINATOR because of its art style and unusual concept. Early on they struggled to fully understand what was happening during combat, but they remained curious and engaged rather than frustrated. As the playthrough continued they became increasingly invested in experimenting with modifiers, upgrading parts, and interacting with progression systems like the Wandering Monk, Temple Priest, and Corpse Monger.",
        "positive": "The creator repeatedly praised the game’s visual style, atmosphere, and originality. They seemed especially excited whenever they discovered stronger body parts or unusual modifier combinations. Throughout the run they actively experimented with different setups and showed clear interest in progression systems and random events. Even while confused at times, they consistently described the game as “cool,” “interesting,” and enjoyable to learn.",
        "negative": "The creator struggled significantly during the early tutorial and repeatedly admitted they did not fully understand what was happening in combat. Several mechanics required experimentation before becoming clear, especially targeting, combat resolution, and modifiers. However, the confusion never escalated into frustration severe enough to stop the playthrough, and understanding improved steadily over time.",
        "directFeedback": "The creator’s strongest feedback centered around the game’s presentation and atmosphere, which immediately captured their interest before they fully understood the mechanics. They openly acknowledged that the systems initially felt confusing, but continued experimenting because the concept and visuals were compelling enough to keep them engaged. As the run progressed they became increasingly focused on buildcrafting and progression systems, suggesting that the game’s long-term depth successfully motivated them to push through the early learning curve."
      },
      "createdAt": "2026-06-03T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-moistcr1tikal-gaming-2026-06-04-1",
      "creatorId": "influencer-moistcr1tikal-gaming",
      "date": "2026-06-04",
      "subscribers": "945K",
      "views": "60K",
      "videoLink": "https://www.youtube.com/watch?v=_NZvue4H_w4&t=1833s",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "Moist Critical became heavily invested in SKINATOR very quickly and treated the game as a serious strategy experience rather than a novelty. Over the course of the two-hour play session he explored progression systems extensively, experimented with builds, revisited shops repeatedly, and became increasingly focused on optimization and long-term planning. Unlike shorter creator videos, this playthrough shows sustained engagement over a very long session and provides strong evidence that the progression loop can retain player interest for extended periods of time.",
        "positive": "The creator repeatedly praised the game’s concept, atmosphere, buildcrafting systems, and progression structure. Loot upgrades consistently generated excitement, especially when discovering powerful combinations or rare parts. He appeared especially engaged with shops, modifiers, rerolls, and progression events, often planning routes specifically around optimization opportunities. Throughout the video he treated the game as deep and strategically rewarding rather than simplistic, and remained highly engaged for nearly two full hours.",
        "negative": "The creator occasionally struggled during the tutorial and early encounters while learning how modifiers, targeting, and positioning interacted. Some systems required experimentation before fully making sense, especially during the onboarding phase. There were also moments where certain mechanics or item interactions were not immediately obvious. However, these issues diminished significantly as the run progressed and never seriously reduced overall enjoyment.",
        "directFeedback": "The creator’s strongest feedback centered around the game’s depth and progression systems. He repeatedly revisited shops, evaluated loot carefully, experimented with different builds, and treated the game as something with substantial long-term strategic potential. Unlike creators who solved encounters using a single dominant strategy, he consistently adapted his approach based on modifiers, enemy setups, economy decisions, and progression opportunities. The length of the session itself became one of the strongest signals of positive engagement, as the creator remained actively interested in the game for almost two hours straight."
      },
      "createdAt": "2026-06-04T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-angel11155-2026-06-06-1",
      "creatorId": "influencer-angel11155",
      "date": "2026-06-06",
      "subscribers": "24.2k",
      "views": "79",
      "videoLink": "https://www.youtube.com/watch?v=IR5zIwwdASM&t=2159s",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator reacted very positively to the game’s concept, repeatedly commenting on how original and strange the idea felt in a good way. They became especially engaged once they started understanding how modifiers and targeting worked together. Loot upgrades, shops, and progression systems consistently generated excitement, and several times they stopped to carefully analyze builds and combinations. Near the end of the video they expressed surprise at how many mechanics, modifiers, and systems the game contained.",
        "positive": "The creator reacted very positively to the game’s concept, repeatedly commenting on how original and strange the idea felt in a good way. They became especially engaged once they started understanding how modifiers and targeting worked together. Loot upgrades, shops, and progression systems consistently generated excitement, and several times they stopped to carefully analyze builds and combinations. Near the end of the video they expressed surprise at how many mechanics, modifiers, and systems the game contained.",
        "negative": "The creator initially struggled to understand several mechanics, especially targeting rules, positioning, and how attack chains interacted. The onboarding process required experimentation and repeated reading before the systems fully clicked. There were also moments where they seemed overwhelmed by the sheer amount of modifiers and effects available later in the run. However, these issues appeared more related to information density than frustration with the game itself.",
        "directFeedback": "The creator directly stated at the beginning that they did not fully understand the game’s concept and repeatedly paused to reason through the mechanics during the tutorial. As the run progressed, however, they became increasingly engaged with strategic decision-making and build optimization. They reacted positively to the growing complexity of the modifier system and near the end specifically commented on how many “crazy things” and interactions existed in the game. Their final impression was that the game was strange, interesting, and surprisingly deep for a demo."
      },
      "createdAt": "2026-06-06T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-squidlord-xd-2026-06-21-1",
      "creatorId": "influencer-squidlord-xd",
      "date": "2026-06-21",
      "subscribers": "122",
      "views": "30",
      "videoLink": "https://www.youtube.com/watch?v=JKFx5FTM0_E",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The streamer quickly became invested in SKINATOR and treated it as a thoughtful strategy game rather than simply another horror-themed indie title. After completing the tutorial they naturally transitioned into experimenting with builds, reading modifiers, and planning upgrades. Throughout the stream they frequently stopped to think through decisions instead of rushing, suggesting they enjoyed engaging with the game's tactical systems. The play session lasted well over an hour, indicating strong sustained engagement.",
        "positive": "The streamer repeatedly complimented the game's atmosphere, presentation, and unusual concept. They became increasingly excited whenever they discovered new body parts, progression events, and opportunities to improve their build. Shops, the Wandering Monk, and the Corpse Monger all generated genuine curiosity rather than feeling like interruptions. They also compared the game's presentation to nostalgic Flash-era strategy games in a positive way and openly stated several times that they were having fun.",
        "negative": "Most criticism centered around learning the game's mechanics during the tutorial rather than problems with the gameplay itself. The streamer occasionally needed to reread modifiers or pause to understand how certain interactions worked before making decisions. However, these moments steadily disappeared as the run progressed. They never expressed frustration with the game's overall design, and confusion generally turned into experimentation rather than disengagement.",
        "directFeedback": "The streamer repeatedly described SKINATOR as fun and became increasingly invested as more progression systems appeared. They enjoyed discovering random events, carefully evaluated purchases in shops, and spent significant time thinking through upgrades instead of choosing them impulsively. Their strongest positive feedback came indirectly through behavior: rather than rushing from encounter to encounter, they willingly slowed down to optimize builds, suggesting the game's strategic depth successfully held their attention throughout the session."
      },
      "createdAt": "2026-06-21T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-shadow-freddy-2026-06-19-1",
      "creatorId": "influencer-shadow-freddy",
      "date": "2026-06-19",
      "subscribers": "5.4K",
      "views": "468",
      "videoLink": "https://www.youtube.com/watch?v=9-GwGwd593c&t=2s",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "The creator skipped the tutorial entirely and attempted to learn the game by experimentation. Instead of becoming frustrated, they spent the early fights actively inspecting modifiers, reading descriptions, and testing different body part arrangements. As the run progressed they became increasingly invested in optimizing builds, interacting with progression events, and evaluating upgrades. Their confidence steadily increased despite the lack of onboarding, making this one of the strongest examples of a player naturally learning the game's systems.",
        "positive": "The creator was immediately attracted by the game's premise, opening the video by saying that the sentence \"Defeat demons. Wear their flesh.\" alone convinced them to play. Throughout the run they enjoyed experimenting with body parts, carefully compared upgrades, and treated every new event as something worth exploring. They spent a surprising amount of time reading modifiers and planning builds, suggesting that the game's strategic systems successfully held their attention even without completing the tutorial.",
        "negative": "Skipping the tutorial naturally caused several moments of confusion during the opening encounters. The creator repeatedly paused to understand support modifiers, attack order, targeting, and positioning before feeling comfortable with combat. However, these moments were handled with curiosity rather than frustration. Instead of criticizing the game, they treated each mechanic as a puzzle to solve and gradually built an understanding through experimentation.",
        "directFeedback": "The creator's strongest feedback came before gameplay even began, stating that the sentence \"Defeat demons. Wear their flesh.\" was enough to sell them on the game. During the run they repeatedly verbalized their reasoning while learning the mechanics and became increasingly engaged with build optimization as more systems appeared. Rather than rushing through encounters, they carefully inspected modifiers, rearranged body parts, and evaluated upgrades, indicating that the strategic depth kept them invested despite intentionally skipping the tutorial."
      },
      "createdAt": "2026-06-19T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    },
    {
      "id": "influencer-video-karab-nn-play-undated-1-1",
      "creatorId": "influencer-karab-nn-play",
      "date": "",
      "subscribers": "",
      "views": "",
      "videoLink": "https://www.youtube.com/watch?v=N71z3vTNFao",
      "values": {
        "tutorialClarity": "",
        "combatUnderstanding": "",
        "modifierUnderstanding": "",
        "lootExcitement": "",
        "strategicDepthPerceived": "",
        "overallEnjoyment": "",
        "replayIntent": "",
        "totalFights": "",
        "saysGameIsFun": "",
        "saysWouldPlayAgain": "",
        "startsTutorial": "",
        "finishesTutorial": "",
        "tutorialDuration": "",
        "firstCombatAfterTutorial": "",
        "firstPartAcquired": "",
        "firstShopEncounter": "",
        "monkDies": "",
        "oborogumoEncounter": "",
        "templePriestEncounter": "",
        "finalBossEncounter": "",
        "wanderingMonkEncounter": "",
        "firstPotionEncounter": "",
        "firstUnderstandingMoment": "",
        "firstExcitementSpike": "",
        "firstCriticism": "",
        "firstGameIsEasyComment": "",
        "firstLootChosen": "",
        "firstBuildModification": "",
        "firstConfusionEvent": "",
        "firstStrategicInsight": "",
        "videoEnds": "",
        "firstCorpseMongerEncounter": ""
      },
      "notes": {
        "overall": "",
        "positive": "",
        "negative": "",
        "directFeedback": ""
      },
      "createdAt": "2026-08-02T00:00:00.000Z",
      "updatedAt": "2026-08-02T00:00:00.000Z"
    }
  ]
};
