const MODIFIER_SEED = (() => {
  const base='assets/modifier-icons/';
  const rows=[
    ['God Eye','Decay','The part in this slot takes 1 damage at the start of their turn.','D','All zones','Triggers at round start','Zone_01_02/UI_Icons_Decay.png'],
    ['God Eye','Confuse','The part in this slot will randomly strike a part from its own chain, dealing 1 damage to it. Only affects attacking parts.','D','All zones','Triggers when combo ends','Zone_01_02/UI_Icons_Confusion.png'],
    ['God Eye','Penitence','Prevents all parts from being rearranged this round.','D','All zones','Triggers immediately','Zone_01_02/Ui_Icons_Penitence.png'],
    ['God Eye','Condemn','The part in this slot cannot receive support modifiers from your head or chest.','D','All zones','Triggers immediately','Zone_01_02/UI_Icons_Condemning.png'],
    ['God Eye','Absolve','The part in this slot is immune to all incoming attack modifiers.','C','All zones','Triggers when attacked','Zone_01_02/UI_Icons_Absolving.png'],
    ['God Eye','Harden','The part in this slot will block all damage to the health pool.','B','All zones','Triggers when attacked','Zone_01_02/UI_Icons_Harden.png'],
    ['God Eye','Blessing','Adds between +1 and +3 attack to any attacking part in this slot.','A','All zones','Triggers immediately','Zone_01_02/UI_Icons_Blessing.png'],
    ['God Eye','Flourish','The part in this slot revives with full health at round start without drawing from the main health pool.','S','All zones','Triggers at start of combo','Zone_01_02/UI_Icons_Flourish.png'],
    ['God Eye','Shield','The part in this slot will block all damage.','S','All zones','Triggers when attacked','Zone_01_02/UI_Icons_Shielding.png'],
    ['God Eye','Relentless','The attacking part strikes its target normally, then targets a second random alive enemy part. Modifiers do not affect the second attack.','S','All zones','Triggers when combo ends','Zone_01_02/UI_Icons_Relentless.png'],
    ['God Eye','Echo','The attacking part in this slot strikes twice. Modifiers do not affect the second attack.','S','All zones','Triggers when combo ends','Zone_01_02/UI_Icons_Echoing.png'],
    ['God Eye','Revenge','The part in this slot gets its base speed duplicated for this round.','S','All zones','Triggers immediately','Zone_01_02/UI_Icons_Revenge.png'],
    ['Attack','Puncturing','Deals 2 damage to the enemy part above the target.','A','Zone 01','Damage — chain modifier','Zone_01_02/UI_Icons_Nailing.png'],
    ['Attack','Hanging','Deals 2 damage to the enemy part below the target.','A','Zone 01','Damage — chain modifier','Zone_01_02/UI_Icons_Hanging.png'],
    ['Attack','Blaze','Deals +2 damage to the target and +1 to the parts directly above and below it.','A','Zone 01','Damage — chain modifier','Zone_01_02/UI_Icons_Blazing.png'],
    ['Attack','Leech','Heals this part for +1 health when it hits.','A','Zone 01','Self-healing modifier','Zone_01_02/UI_Icons_Leeching.png'],
    ['Attack','Transfusion','Refills your health pool by an amount equal to this part’s current damage.','S','Zone 01','Self-healing modifier','Zone_01_02/UI_Icons_Transfusing.png'],
    ['Attack','Reaping','When the target is disabled by this hit, this part fully heals without drawing from the health pool.','S','Zone 01','Self-healing modifier','Zone_01_02/UI_Icons_Reaping.png'],
    ['Attack','Lacerate','Deals +1 damage to all enemy parts above the target.','S','Zone 01','Damage — chain modifier','Zone_01_02/UI_Icons_Lacerating.png'],
    ['Attack','Corrupt','Deals +1 damage to all enemy parts below the target.','S','Zone 01','Damage — chain modifier','Zone_01_02/UI_Icons_Corrupting.png'],
    ['Attack','Curse','Removes all active support modifiers from the target for this round.','C','Zones 01 + 02','Debuff modifier','Zone_01_02/UI_Icons_Curse.png'],
    ['Attack','Marking','After this hit, the target takes +1 extra damage from any attack for the rest of the round.','C','Zones 01 + 02','Damage — chain modifier','Zone_01_02/UI_Icons_Marking.png'],
    ['Attack','Shattering','If the target is receiving a support modifier, deal +1 damage.','C','Zones 01 + 02','Damage — chain modifier','Zone_01_02/UI_Icons_Shattering.png'],
    ['Attack','Tormenting','If the target does not have full health, deal 1 extra damage.','B','Zones 01 + 02','Damage — chain modifier','Zone_01_02/UI_Icons_Tormenting.png'],
    ['Attack','Smite','If the target’s health is full, deal +1 extra damage.','B','Zones 01 + 02','Damage — chain modifier','Zone_01_02/UI_Icons_Smite.png'],
    ['Attack','Backstab','Deals +2 damage to a random enemy part.','A','Zones 01 + 02','Damage — chain modifier','Zone_01_02/UI_Icons_Backstabbing.png'],
    ['Attack','Frigid','Reduces target speed by 1. Speed resets after the target becomes disabled.','A','Zones 01 + 02','Debuff modifier','Zone_01_02/UI_Icons_Frigid.png'],
    ['Attack','Retribution','If this hit disables the target, the next attacking part in your chain gains +2 attack this round.','A','Zones 01 + 02','Damage — chain modifier','Zone_01_02/UI_Icons_Retribution.png'],
    ['Attack','Stigmatizing','The target takes +1 extra damage directly to the health pool from any attack for the rest of the round.','A','Zones 01 + 02','Damage modifier','Zone_01_02/UI_Icons_Stigmatazing.png'],
    ['Attack','Draining','Transfusion only on dead parts.','C','Zone 02','','Zone02_Unique/UI_Icons_Draining.png'],
    ['Attack','Enraged','Deal +1 damage per every 2 missing health points on this part.','C','Zone 02','','Zone02_Unique/UI_Icons_enraged.png'],
    ['Attack','Exploitation','Deals +1 damage for every 2 missing health points the target has.','A','Zone 02','','Zone02_Unique/UI_Icons_Exploitation.png'],
    ['Attack','Bury','Deals 3 extra damage when attacking a dead part.','A','Zone 02','','Zone02_Unique/UI_Icons_Burrial.png'],
    ['Attack','Hope','This part gains +5 damage if your health bar is at 0.','A','Zone 02','','Zone02_Unique/UI_Icons_Hope.png'],
    ['Attack','Envy','Deals +1 extra damage to part health per modifier on the target.','B','Zone 02','','Zone02_Unique/UI_Icons_Envy.png'],
    ['Attack','Infect','If this attack disables a part, deal 4 damage to the part above.','B','Zone 02','','Zone02_Unique/UI_Icons_Infecting.png'],
    ['Attack','Disinfect','If this attack disables a part, deal 4 damage to the part below.','B','Zone 02','','Zone02_Unique/UI_Icons_Desinfect.png'],
    ['Attack','Cremation','Deal 1 damage above and below the target if it is knocked out by this attack. Repeat if indirect damage knocks out another part.','B','Zone 01','','Zone02_Unique/UI_Icons_Cremation.png'],
    ['Support','Harmony','If all parts in range share the same modifier, each gains +2 damage this round.','C','Zone 01','Enhances damage','Zone_01_02/UI_Icons_Harmony.png'],
    ['Support','Propagate','Extends the range of other support parts within range by 1 slot.','B','Zone 01','Overall enhancement','Zone_01_02/UI_Icons_Propagate.png'],
    ['Support','Anoint','Makes all parts in range trigger a random attack modifier twice on attack.','S','Zone 01','Enhances damage','Zone_01_02/UI_Icons_Anoint.png'],
    ['Support','Empower','Adds +1 attack to all parts in range.','S','Zones 01 + 02','','Zone_01_02/UI_Icons_Empowering.png'],
    ['Support','Fortify','Parts in range ignore one instance of damage when the part’s health is 1.','B','Zones 01 + 02','Enhances defence','Zone_01_02/UI_Icons_Fortify.png'],
    ['Support','Lineage','Parts in range gain +1 attack for each active support part above them.','B','Zones 01 + 02','Enhances damage','Zone_01_02/UI_Icons_Lineage.png'],
    ['Support','Protection','All parts in range ignore the first instance of damage.','A','Zones 01 + 02','Enhances defence','Zone_01_02/UI_Icons_Protection.png'],
    ['Support','Heal','Restores 1 health to all parts in range at the beginning of the turn.','A','Zones 01 + 02','','Zone_01_02/UI_Icons_Healing.png'],
    ['Support','Swift','Duplicates the base speed of parts within range. Does not stack.','S','Zones 01 + 02','','Zone_01_02/UI_Icons_Swift.png'],
    ['Support','Undead','Revived parts within range gain +2 attack this round. They must be in range when revived.','B','Zone 02','','Zone02_Unique/UI_Icons_Undead.png'],
    ['Support','Desperation','Each part in range gains +1 power for each disabled part in your body-parts chain.','A','Zone 02','','Zone02_Unique/UI_Icons_Desperation.png'],
    ['Support','Propulsion','Any part in range gains 3 speed per disabled part above it.','A','Zone 02','','Zone02_Unique/UI_Modifier_Propulsion.png'],
    ['Support','Ruthless','Each part in range gains +1 power for each disabled part in the enemy body-parts chain.','S','Zone 02','','Zone02_Unique/UI_Icons_Ruthless.png'],
    ['Support','Resonate','All parts in range with the same current speed as this supporting part gain +2 attack power.','C','Zone 02','','Zone02_Unique/UI_Icons_Resonate.png'],
    ['Heart','Left Stomp','Left leg repeats all.','C','','','Zone02_Unique/UI_Icons_LeftLeg_Repeater.png'],
    ['Heart','Right Stomp','Right leg repeats all.','C','','','Zone02_Unique/UI_Icons_RightLeg_Repeater.png'],
    ['Heart','Right Smash','Right arm repeats all.','C','','','Zone02_Unique/UI_Icons_RightHand_Repeater.png'],
    ['Heart','Left Smash','Left arm repeats all.','C','','','Zone02_Unique/UI_Icons_LeftHand_Repeater.png'],
    ['Heart','Right Reflex','Right limbs repeat.','B','','','Zone02_Unique/UI_Icons_RightLimbs_Repeater.png'],
    ['Heart','Left Reflex','Left limbs repeat.','B','','','Zone02_Unique/UI_Icons_LeftLimbs_Repeater.png'],
    ['Heart','Barrage','Repeater arms.','B','','','Zone02_Unique/UI_Icons_Barrage.png'],
    ['Heart','Stampede','Repeater legs.','B','','','Zone02_Unique/UI_Icons_Stampede.png'],
    ['Heart','Siphon','Damages all parts in range by 1 and refills the health pool by 2 for each damage.','A','','','Zone02_Unique/UI_Icons_Siphon.png'],
    ['Heart','Calling','For every disabled part in range, add +5 speed to this supporting part.','A','','','Zone02_Unique/UI_Icons_Calling.png'],
    ['Heart','Brute Force','Repeats all base damage without modifiers.','A','','','Zone02_Unique/UI_Icons_BruteForce.png'],
    ['Heart','Bravery','All attacking parts in range gain +1 for every attacking part in range.','S','','','Zone02_Unique/UI_Icons_Bravery.png'],
    ['Heart','Rebirth','Fully heals all non-disabled parts in range.','S','','','Zone02_Unique/UI_Icons_Rebirth.png'],
    ['Heart','Momentum','Combines the speed of all parts in range and applies it to every part in range.','S','','','Zone02_Unique/UI_Icons_Momentum.png'],
    ['Heart','Repeater','Repeats all attacks in range, including modifiers, twice.','S+','','','Zone02_Unique/UI_Icons_Repeater.png']
  ];
  return rows.map((r,i)=>({id:`mod-${i+1}`,category:r[0],name:r[1],description:r[2],grade:r[3],zone:r[4],trigger:r[5],icon:base+r[6],iconData:'',superEnabled:false,superName:'',superDescription:'',updatedAt:new Date().toISOString()}));
})();
const SPAWN_ICON_BASE='assets/modifier-icons/Spawns/Spawn_Modifiers/';
const SPAWN_MODIFIER_SEED = [
  ['spawn-mod-11','Offensive','Ravage','YOUR FIRST ATTACK DEALS +5 <color=red>DAMAGE</color>.','UI_SpawnMod_Ravage.png'],
  ['spawn-mod-4','Offensive','Execution','YOUR LAST ATTACK DEALS +5 <color=red>DAMAGE</color>.','UI_SpawnMod_Execute.png'],
  ['spawn-mod-9','Offensive','Immobilize','THE FIRST ENEMY PART HIT LOSES ALL <color=white>SPEED</color>. RESETS AFTER DISABLED.','UI_SpawnMod_Immobilize.png'],
  ['spawn-mod-5','Offensive','Expose','THE FIRST ENEMY PART HIT TAKES DOUBLE <color=red>DAMAGE</color> FROM THE NEXT ATTACK.','UI_SpawnMod_Expose.png'],
  ['spawn-mod-6','Offensive','Feast','REFILL 1 <color=green>HEALTH</color> TO YOUR <color=green>HEALTH POOL</color> FOR EACH DISABLED ENEMY PART.','UI_SpawnMod_Feast.png'],
  ['spawn-mod-13','Offensive','Sacrifice','REFILL 1 <color=green>HEALTH</color> TO YOUR <color=green>HEALTH POOL</color> FOR EACH DISABLED PART ON YOUR BODY PART CHAIN.','UI_SpawnMod_Sacrifice.png'],
  ['spawn-mod-8','Offensive','Hunger','YOUR FIRST ATTACK DEALS DOUBLE <color=red>DAMAGE</color> AGAINST DISABLED PARTS.','UI_SpawnMod_Hunger.png'],
  ['spawn-mod-2','Offensive','Detonate','IF YOUR FIRST ATTACK TARGETS A DISABLED PART, DEAL 1 <color=red>DAMAGE</color> TO ALL PARTS ABOVE AND BELOW IT.','UI_SpawnMod_Detonate.png'],
  ['spawn-overkill','Offensive','Overkill','IF YOUR FIRST ATTACK DISABLES A PART, DOUBLE THE <color=red>DAMAGE</color> DEALT.',''],
  ['spawn-mod-1','Offensive','Annihilate','YOUR FIRST ATTACK WILL DISABLE ITS TARGET.','UI_SpawnMod_ANNIHILATE.png'],
  ['spawn-mod-14','Defensive','Thorns','THE FIRST INSTANCE OF <color=red>DAMAGE</color> THIS ROUND IS REFLECTED INTO THE ENEMY <color=green>HEALTH POOL</color>.','UI_SpawnMod_Thorns.png'],
  ['spawn-mod-12','Defensive','Resurrection','THE FIRST DISABLED PART IN YOUR CHAIN REVIVES IMMEDIATELY.','UI_SpawnMod_Resurrection.png'],
  ['spawn-mod-3','Defensive','Endure','THE FIRST PART ATTACKED BY THE ENEMY CANNOT BE DISABLED THIS ROUND.','UI_SpawnMod_Endure.png'],
  ['spawn-mod-10','Defensive','Mirror','REFLECT THE FIRST 6 <color=red>DAMAGE</color> RECEIVED THIS ROUND INTO THE ENEMY <color=green>HEALTH POOL</color>.','UI_SpawnMod_Mirror.png'],
  ['spawn-haste','Defensive','Haste','ALL YOUR ACTIVE PARTS GAIN +5 <color=white>SPEED</color> THIS ROUND.',''],
  ['spawn-sanctuary','Defensive','Sanctuary','YOUR HEAD AND CHEST CANNOT TAKE <color=red>DAMAGE</color> THIS ROUND.',''],
  ['spawn-martyrdom','Defensive','Martyrdom','WHEN ONE OF YOUR PARTS IS DISABLED THIS ROUND, REFILL 3 <color=green>HEALTH</color> TO YOUR <color=green>HEALTH POOL</color>.',''],
  ['spawn-frenzy','Defensive','Frenzy','ALL ACTIVE ATTACKING PARTS RECEIVE 2 EXTRA DAMAGE THIS ROUND.',''],
  ['spawn-reanimation','Defensive','Reanimation','REVIVE ALL DISABLED PARTS WITH FULL <color=green>HEALTH</color> BUT 0 <color=white>SPEED</color>.',''],
  ['spawn-expansion','Defensive','Expansion','ALL SUPPORT PARTS GAIN 3 <color=yellow>RANGE</color> THIS ROUND.',''],
  ['spawn-greed','Passive','Greed','GAIN 30% MORE GOLD FROM BATTLES.',''],
  ['spawn-bargain','Passive','Bargain','SHOP PRICES ARE 30% CHEAPER.',''],
  ['spawn-ambush','Passive','Ambush','ALWAYS ATTACK FIRST ON THE FIRST ROUND OF A FIGHT.',''],
  ['spawn-brutality','Passive','Brutality','DEAL +5 <color=red>DAMAGE</color> WHEN YOU SKINATE AN ENEMY.',''],
  ['spawn-consume','Passive','Consume','WHEN YOU SKINATE AN ENEMY, REFILL 5 <color=green>HEALTH</color> TO YOUR <color=green>HEALTH POOL</color>.',''],
  ['spawn-instinct','Passive','Instinct','ALL YOUR PARTS START EACH FIGHT WITH +1 <color=white>SPEED</color>.',''],
  ['spawn-parasite','Passive','Parasite','WHEN YOU DISABLE AN ENEMY PART, REFILL 1 <color=green>HEALTH</color> TO YOUR <color=green>HEALTH POOL</color>.',''],
  ['spawn-vengeance','Passive','Vengeance','IF YOU GET SKINATED, ALL PARTS GET REVENGE (DOUBLE SPEED).',''],
  ['spawn-desperation','Passive','Desperation','ALL YOUR PARTS GAIN +1 <color=red>ATTACK</color> WHILE YOUR <color=green>HEALTH POOL</color> IS BELOW 50%.',''],
  ['spawn-adrenaline','Passive','Adrenaline','WHEN YOUR <color=green>HEALTH POOL</color> DROPS BELOW 50%, ALL YOUR PARTS GAIN +2 <color=white>SPEED</color>.','']
].map(([id,category,name,description,icon])=>({id,category,name,description,icon:icon?SPAWN_ICON_BASE+icon:''}));
