// Clickable, reversible, multi-column sorting for both task boards.
const TASK_SORT_KEY='skinator-task-multi-sort-v1';
const taskSortState=(()=>{try{return JSON.parse(localStorage.getItem(TASK_SORT_KEY))||{ongoing:[],finished:[]}}catch{return{ongoing:[],finished:[]}}})();
const taskSortableColumns=[['priority','PRIORITY'],['task','TASK'],['category','CATEGORY'],['operator','OPERATOR'],['status','STATUS'],['implementationStatus','IMPLEMENTATION']];
$('ongoingSort').hidden=true;$('finishedSort').hidden=true;
$('ongoingSort').insertAdjacentHTML('afterend','<button type="button" class="mini clear-task-sorting" data-clear-task-sort="ongoing">CLEAR SORTING</button>');
$('finishedSort').insertAdjacentHTML('afterend','<button type="button" class="mini clear-task-sorting" data-clear-task-sort="finished">CLEAR SORTING</button>');

function saveTaskSort(){localStorage.setItem(TASK_SORT_KEY,JSON.stringify(taskSortState))}
function taskSortHeader(mode){const active=taskSortState[mode]||[];return `<div class="task-line task-header">${taskSortableColumns.map(([field,label])=>{const index=active.findIndex(rule=>rule.field===field),rule=active[index];return `<div><button class="task-sort-heading ${rule?'active':''}" data-task-sort="${field}" data-sort-board="${mode}">${label}${rule?` <em>${index+1}</em><i>${rule.direction==='asc'?'▲':'▼'}</i>`:''}</button></div>`}).join('')}<div>NOTES</div></div>`}
function compareTaskValues(a,b,field){if(field==='priority')return (priorityOrder[a.priority]??99)-(priorityOrder[b.priority]??99);if(field==='status'||field==='implementationStatus')return (statusOrder[a[field]]??99)-(statusOrder[b[field]]??99);return String(a[field]||'').localeCompare(String(b[field]||''),undefined,{numeric:true,sensitivity:'base'})}
function applyTaskMultiSort(rows,mode){const rules=taskSortState[mode]||[];if(!rules.length)return rows;return [...rows].sort((a,b)=>{for(const rule of rules){const result=compareTaskValues(a,b,rule.field);if(result)return rule.direction==='asc'?result:-result}return 0})}
function taskBoardRows(rows,mode){return taskSortHeader(mode)+rows.map(record=>`<article class="task-line" style="--task-category:${taskCategoryColor(record.category)}"><div>${enhancedTaskSelect('priority',record.priority,taskPriorities,record.id)}</div><div class="task-title" data-business="task" data-id="${record.id}">${escapeHtml(record.task)}</div><div>${enhancedTaskSelect('category',record.category,taskOptions('category'),record.id)}</div><div>${enhancedTaskSelect('operator',record.operator,taskOptions('operator'),record.id)}</div><div>${enhancedTaskSelect('status',record.status,taskStatuses,record.id)}</div><div>${enhancedTaskSelect('implementationStatus',record.implementationStatus,taskStatuses,record.id)}</div><div class="task-title" data-business="task" data-id="${record.id}">${escapeHtml(record.notes||'—')}</div></article>`).join('')}
function bindTaskSortHeaders(grid){grid.querySelectorAll('[data-task-sort]').forEach(button=>button.onclick=()=>{const mode=button.dataset.sortBoard,field=button.dataset.taskSort,rules=taskSortState[mode]||(taskSortState[mode]=[]),existing=rules.find(rule=>rule.field===field);if(existing)existing.direction=existing.direction==='asc'?'desc':'asc';else rules.push({field,direction:'asc'});saveTaskSort();mode==='ongoing'?renderOngoing():renderFinished()})}
document.querySelectorAll('[data-clear-task-sort]').forEach(button=>button.onclick=()=>{const mode=button.dataset.clearTaskSort;taskSortState[mode]=[];saveTaskSort();mode==='ongoing'?renderOngoing():renderFinished();toast('SORTING CLEARED')});

renderOngoing=function(){const query=($('ongoingSearch').value||'').toLowerCase(),priority=$('ongoingPriority').value,status=$('ongoingStatus').value;let rows=ongoingTaskRecords.filter(record=>!taskIsFullyFinished(record)&&`${record.task} ${record.notes} ${record.category} ${record.operator}`.toLowerCase().includes(query)&&(priority==='All'||record.priority===priority)&&(status==='All'||record.status===status));rows=applyTaskMultiSort(rows,'ongoing');$('navOngoingCount').textContent=ongoingTaskRecords.filter(record=>!taskIsFullyFinished(record)).length;$('ongoingResultCount').textContent=plural(rows.length,'TASK');$('ongoingGrid').innerHTML=taskBoardRows(rows,'ongoing');bindTaskBoard($('ongoingGrid'));bindTaskSortHeaders($('ongoingGrid'))};
renderFinished=function(){const query=($('finishedSearch').value||'').toLowerCase();let rows=ongoingTaskRecords.filter(record=>taskIsFullyFinished(record)&&`${record.task} ${record.notes} ${record.category} ${record.operator}`.toLowerCase().includes(query));rows=applyTaskMultiSort(rows,'finished');$('navFinishedCount').textContent=ongoingTaskRecords.filter(taskIsFullyFinished).length;$('finishedResultCount').textContent=plural(rows.length,'FINISHED TASK');$('finishedGrid').innerHTML=rows.length?taskBoardRows(rows,'finished'):'<div class="business-empty">NO FINISHED TASKS YET</div>';bindTaskBoard($('finishedGrid'));bindTaskSortHeaders($('finishedGrid'))};
renderOngoing();renderFinished();
