const PLANNER_KEY='skinator-planner-v1';
const ROSTER_VIEW_KEY='skinator-roster-view-v1';
const rosterView=publishedSnapshot?.rosterView||(()=>{try{return JSON.parse(localStorage.getItem(ROSTER_VIEW_KEY))||{showVariants:false,showSpawns:false}}catch{return{showVariants:false,showSpawns:false}}})();
const planner=publishedSnapshot?.planner||(()=>{try{return JSON.parse(localStorage.getItem(PLANNER_KEY))||{customTasks:[],schedule:{},month:new Date().toISOString().slice(0,7)}}catch{return{customTasks:[],schedule:{},month:new Date().toISOString().slice(0,7)}}})();
const savePlanner=()=>{localStorage.setItem(PLANNER_KEY,JSON.stringify(planner));window.skinatorCloudSave?.()};

document.querySelector('aside nav .nav:disabled')?.remove();
document.querySelector('aside nav').insertAdjacentHTML('beforeend','<button class="nav" data-tab="parasytes"><i>◉</i> PARASYTES <span id="navParasyteCount">42</span></button><button class="nav" data-tab="tracker"><i>▦</i> TRACKER <span id="navTaskCount">0</span></button>');
document.querySelector('main').insertAdjacentHTML('beforeend',`<section id="trackerView" hidden>
  <div class="tracker-top"><div class="tracker-metrics"><article><label>OPEN TASKS</label><b id="trackerOpen">0</b><small>NEED ATTENTION</small></article><article><label>SCHEDULED</label><b id="trackerScheduled">0</b><small>ON THE CALENDAR</small></article><article><label>COMPLETED</label><b id="trackerDone">0</b><small>SOURCE-SYNCED</small></article></div></div>
  <div class="tracker-layout"><aside class="task-backlog" id="taskBacklog"><div class="backlog-head"><div><small>UNSCHEDULED</small><h2>Task Backlog</h2></div><button class="mini" id="inlineNewTask">＋ TASK</button></div><p>Drag incomplete work onto any calendar day.</p><div id="backlogTasks" class="backlog-tasks"></div></aside>
  <section class="calendar-panel"><div class="calendar-head"><button class="calendar-nav" id="prevMonth">‹</button><div><small>PRODUCTION CALENDAR</small><h2 id="calendarTitle"></h2></div><button class="calendar-nav" id="nextMonth">›</button><button class="mini today-button" id="todayMonth">TODAY</button></div><div class="weekday-row"><span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span><span>SAT</span><span>SUN</span></div><div id="calendarGrid" class="calendar-grid"></div></section></div>
  <form id="customTaskForm" class="custom-task-form" hidden><div><small>NEW CUSTOM TASK</small><h2>Add to backlog</h2></div><label>TASK NAME *<input id="customTaskTitle" required placeholder="e.g. Polish Graveyard lighting"></label><label>TYPE<select id="customTaskType"><option>Art</option><option>Design</option><option>Code</option><option>Audio</option><option>Marketing</option><option>Other</option></select></label><label>ESTIMATED DAYS<input id="customTaskDays" type="number" min="1" max="365" value="1"></label><button class="btn ghost" type="button" id="cancelCustomTask">CANCEL</button><button class="btn red" type="submit">CREATE TASK</button></form>
</section>`);
document.querySelector('main').insertAdjacentHTML('beforeend',`<section id="parasytesView" hidden><div class="stats"><article><label>PARASYTE NODES</label><b id="parasyteCount">42</b><small>ALL LEVELS</small></article><article><label>COMPLETE FAMILIES</label><b id="parasyteFamilyComplete">0/12</b><small>EVERY LEVEL COMPLETE</small></article><article><label>COMPLETE PARASYTES</label><b id="parasyteCompleteCount">0/42</b><small>GIF + DESCRIPTION + IN GAME</small></article><article><label>WITH GIF</label><b id="parasyteGifCount">0</b><small>500 × 500 ASSETS</small></article></div><section class="panel"><div class="toolbar"><label class="search">⌕ <input id="parasyteSearch" placeholder="SEARCH PARASYTES"></label><span id="parasyteResultCount"></span></div><div id="parasyteFamilies" class="parasyte-families"></div></section></section>`);
document.body.insertAdjacentHTML('beforeend',`<dialog id="parasyteDialog"><form id="parasyteForm"><div class="dialog-head"><div><p>PARASYTE DATABASE</p><h2 id="parasyteDialogTitle"></h2></div><button type="button" class="x" id="closeParasyte">×</button></div><div class="dialog-body"><div class="parasyte-editor"><label class="parasyte-upload drop-target" id="parasyteGifDrop"><input id="parasyteGifInput" type="file" accept="image/gif" hidden><img id="parasyteGifPreview" hidden><span id="parasyteGifPrompt">＋ CLICK OR DROP<br>500 × 500 GIF</span></label><div><label>FAMILY<input id="parasyteFamily" readonly></label><label>LEVEL<input id="parasyteLevel" readonly></label><label>DESCRIPTION<textarea id="parasyteDescription" rows="5"></textarea></label><label>ESTIMATED DAYS TO FINISH<input id="parasyteEstimatedDays" type="number" min="1" max="365" value="1"></label><label class="parasyte-implemented"><span>GAME STATUS</span><span class="check-row"><input id="parasyteImplemented" type="checkbox"> IMPLEMENTED INTO THE GAME</span></label><button type="button" class="remove" id="removeParasyteGif">REMOVE GIF</button></div></div></div><div class="dialog-actions"><span></span><span></span><button type="button" class="btn ghost" id="cancelParasyte">CANCEL</button><button class="btn red" type="submit">SAVE PARASYTE</button></div></form></dialog>`);

let parasytes=(publishedSnapshot?.parasytes||PARASYTE_SEED).map(p=>({...p})),editingParasyteId=null,editingParasyteGif='';
const openParasyteDatabase=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('skinator-parasyte-database',1);request.onupgradeneeded=()=>request.result.createObjectStore('data');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
async function loadParasytes(){if(publishedSnapshot){renderParasytes();renderTracker();return}try{const db=await openParasyteDatabase(),saved=await new Promise((resolve,reject)=>{const req=db.transaction('data','readonly').objectStore('data').get('all');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();if(saved){const byId=new Map(saved.map(p=>[p.id,p]));parasytes=PARASYTE_SEED.map(seed=>({...seed,...(byId.get(seed.id)||{})}))}renderParasytes();renderTracker()}catch(error){console.error(error);toast('PARASYTE STORAGE COULD NOT BE OPENED')}}
async function saveParasytes(){try{const db=await openParasyteDatabase();await new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(parasytes,'all');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();window.skinatorCloudSave?.()}catch(error){console.error(error);toast('PARASYTE SAVE FAILED')}}
const parasyteIsComplete=p=>!!p.gif&&!!p.description?.trim()&&!!p.implemented;
function renderParasytes(){const query=($('parasyteSearch')?.value||'').toLowerCase(),filtered=parasytes.filter(p=>`${p.family} ${p.level} ${p.description}`.toLowerCase().includes(query)),families=[...new Set(filtered.map(p=>p.family))],allFamilies=[...new Set(parasytes.map(p=>p.family))],completeCount=parasytes.filter(parasyteIsComplete).length,completeFamilies=allFamilies.filter(family=>parasytes.filter(p=>p.family===family).every(parasyteIsComplete)).length;$('parasyteCount').textContent=parasytes.length;$('navParasyteCount').textContent=parasytes.length;$('parasyteGifCount').textContent=parasytes.filter(p=>p.gif).length;$('parasyteCompleteCount').textContent=`${completeCount}/${parasytes.length}`;$('parasyteFamilyComplete').textContent=`${completeFamilies}/${allFamilies.length}`;$('parasyteResultCount').textContent=plural(filtered.length,'NODE');$('parasyteFamilies').innerHTML=families.map(family=>{const familyNodes=filtered.filter(p=>p.family===family),familyComplete=parasytes.filter(p=>p.family===family).every(parasyteIsComplete);return`<section class="parasyte-family ${familyComplete?'complete-family':''}"><div class="family-heading"><span>PARASYTE FAMILY</span><h2>${escapeHtml(family)}</h2><small>${familyComplete?'FAMILY COMPLETE':`${familyNodes.length} LEVELS`}</small></div><div class="parasyte-grid">${familyNodes.map(p=>{const complete=parasyteIsComplete(p);return`<article class="parasyte-card level-${p.level.toLowerCase()} ${complete?'complete':''}" data-id="${p.id}"><div class="parasyte-visual">${p.gif?`<img src="${p.gif}" alt="${escapeHtml(p.family)} ${p.level}">`:'<span class="parasyte-placeholder">◉</span>'}<b>${p.level.toUpperCase()}</b><em class="parasyte-status">${complete?'COMPLETE':'INCOMPLETE'}</em></div><div class="parasyte-info"><h3>${escapeHtml(p.family)}</h3><p>${escapeHtml(p.description)}</p><span>${p.gif?'GIF READY':'GIF MISSING'} // ${p.implemented?'IN GAME':'NOT IN GAME'}</span></div></article>`}).join('')}</div></section>`}).join('');document.querySelectorAll('.parasyte-card').forEach(card=>card.onclick=()=>openParasyte(card.dataset.id))}
function openParasyte(id){const p=parasytes.find(x=>x.id===id);if(!p)return;editingParasyteId=id;editingParasyteGif=p.gif||'';$('parasyteDialogTitle').textContent=`${p.level} ${p.family}`;$('parasyteFamily').value=p.family;$('parasyteLevel').value=p.level;$('parasyteDescription').value=p.description;$('parasyteEstimatedDays').value=p.estimatedDays||1;$('parasyteImplemented').checked=!!p.implemented;setPreview('parasyteGifPreview','parasyteGifPrompt',editingParasyteGif);$('removeParasyteGif').hidden=!editingParasyteGif;$('parasyteDialog').showModal()}
function acceptParasyteGif(file){if(!file||file.type!=='image/gif')return toast('PARASYTE ASSETS MUST BE GIF FILES');fileData(file,data=>{const img=new Image();img.onload=()=>{if(img.naturalWidth!==500||img.naturalHeight!==500)return toast(`INVALID SIZE — ${img.naturalWidth}×${img.naturalHeight}. REQUIRED 500×500`);editingParasyteGif=data;setPreview('parasyteGifPreview','parasyteGifPrompt',data);$('removeParasyteGif').hidden=false};img.src=data})}
$('parasyteSearch').oninput=renderParasytes;$('parasyteGifInput').onchange=e=>acceptParasyteGif(e.target.files[0]);setupDrop($('parasyteGifDrop'),acceptParasyteGif);$('removeParasyteGif').onclick=()=>{editingParasyteGif='';setPreview('parasyteGifPreview','parasyteGifPrompt','');$('removeParasyteGif').hidden=true};$('closeParasyte').onclick=$('cancelParasyte').onclick=()=>$('parasyteDialog').close();$('parasyteForm').onsubmit=e=>{e.preventDefault();const p=parasytes.find(x=>x.id===editingParasyteId);if(p){p.description=$('parasyteDescription').value.trim();p.gif=editingParasyteGif;p.estimatedDays=+$('parasyteEstimatedDays').value||1;p.implemented=$('parasyteImplemented').checked;saveParasytes();renderParasytes();renderTracker();$('parasyteDialog').close();toast('PARASYTE UPDATED')}};loadParasytes();

const characterCore=$('bossCharacter').closest('.form-section');characterCore.insertAdjacentHTML('beforeend','<div class="planning-fields"><label>ESTIMATED DAYS TO FINISH<input id="characterEstimatedDays" type="number" min="1" max="365" placeholder="1"></label><label class="boss-check"><span>COMPLETION OVERRIDE</span><span class="check-row"><input id="characterForceComplete" type="checkbox"> FORCE CHARACTER COMPLETE</span></label></div>');
$('completionFilter').insertAdjacentHTML('afterend','<div class="roster-view-switches"><label><input id="globalVariantNodes" type="checkbox"> DISPLAY VARIANTS</label><label><input id="globalSpawnView" type="checkbox"> DISPLAY SPAWNS</label></div>');
$('globalVariantNodes').checked=!!rosterView.showVariants;$('globalSpawnView').checked=!!rosterView.showSpawns;
$('npcDescription').closest('div').insertAdjacentHTML('beforeend','<div class="planning-fields npc-planning-fields"><label>ZONE<select id="npcZone"><option value="Graveyard">GRAVEYARD</option><option value="Zoo">ZOO</option></select></label><label>ESTIMATED DAYS TO FINISH<input id="npcEstimatedDays" type="number" min="1" max="365" placeholder="1"></label><label class="boss-check"><span>COMPLETION OVERRIDE</span><span class="check-row"><input id="npcForceComplete" type="checkbox"> FORCE NPC COMPLETE</span></label></div>');

const originalOpenCharacter=openCharacter;openCharacter=function(id=null){originalOpenCharacter(id);const c=state.characters.find(x=>x.id===id);$('characterEstimatedDays').value=c?.estimatedDays||'';$('characterForceComplete').checked=!!c?.forceComplete};
const originalRenderVariantEditor=renderVariantEditor;renderVariantEditor=function(){originalRenderVariantEditor();document.querySelectorAll('.variant-item input[type="text"]').forEach(input=>input.placeholder='Variant file name')};
const originalOpenNpc=openNpc;openNpc=function(id=null){originalOpenNpc(id);const n=state.npcs.find(x=>x.id===id);$('npcZone').value=n?.zone||'Graveyard';$('npcEstimatedDays').value=n?.estimatedDays||'';$('npcForceComplete').checked=!!n?.forceComplete};

$('characterForm').addEventListener('submit',()=>{const id=state.editingChar,fileName=$('fileName').value.trim(),days=+$('characterEstimatedDays').value||1,forced=$('characterForceComplete').checked;setTimeout(()=>{const c=state.characters.find(x=>x.id===id)||(state.characters.find(x=>x.fileName===fileName));if(c){c.estimatedDays=days;c.forceComplete=forced;save();render();renderTracker()}},0)},true);
$('npcForm').addEventListener('submit',()=>{const id=state.editingNpc,name=$('npcName').value.trim(),zone=$('npcZone').value||'Graveyard',days=+$('npcEstimatedDays').value||1,forced=$('npcForceComplete').checked;setTimeout(()=>{const n=state.npcs.find(x=>x.id===id)||(state.npcs.find(x=>x.name===name));if(n){n.zone=zone;n.estimatedDays=days;n.forceComplete=forced;if(forced){n.production=Object.fromEntries(productionTasks.map(t=>[t,true]));n.unity=Object.fromEntries(unityTasks.map(t=>[t,true]))}save();render();renderTracker()}},0)},true);

function plannerTasks(){const characters=state.characters.map(c=>({id:`character:${c.id}`,source:'Character',sourceId:c.id,title:c.gameName||c.fileName||'Unnamed character',days:c.estimatedDays||1,complete:completionFor(c).complete}));const npcs=state.npcs.map(n=>({id:`npc:${n.id}`,source:'NPC',sourceId:n.id,title:n.name||'Unnamed NPC',days:n.estimatedDays||1,complete:npcStatus(n).complete}));const parasyteTasks=parasytes.map(p=>({id:`parasyte:${p.id}`,source:'Parasyte',sourceId:p.id,title:`${p.level} ${p.family}`,days:p.estimatedDays||1,complete:parasyteIsComplete(p)}));const custom=planner.customTasks.map(t=>({...t,source:t.type||'Custom'}));return[...characters,...npcs,...parasyteTasks,...custom]}
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function taskCard(t,calendar=false){return `<article class="planner-task ${t.complete?'done':''} ${calendar?'compact':''}" draggable="true" data-task-id="${t.id}"><span class="task-type">${escapeHtml(t.source)}</span><b>${escapeHtml(t.title)}</b><small>${t.days} DAY${t.days===1?'':'S'} ${t.complete?'// COMPLETE':''}</small>${t.id.startsWith('custom:')?`<button type="button" class="task-done" data-complete-id="${t.id}" title="Toggle complete">✓</button>`:''}</article>`}
function renderTracker(){const tasks=plannerTasks(),scheduled=new Set(Object.keys(planner.schedule)),open=tasks.filter(t=>!t.complete),done=tasks.filter(t=>t.complete);$('navTaskCount').textContent=open.length;$('trackerOpen').textContent=open.length;$('trackerScheduled').textContent=tasks.filter(t=>scheduled.has(t.id)).length;$('trackerDone').textContent=done.length;$('backlogTasks').innerHTML=open.filter(t=>!scheduled.has(t.id)).map(t=>taskCard(t)).join('')||'<div class="backlog-empty">ALL OPEN WORK IS SCHEDULED</div>';renderCalendar(tasks);bindTaskInteractions()}
function renderCalendar(tasks){const [year,month]=planner.month.split('-').map(Number),first=new Date(year,month-1,1),start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));$('calendarTitle').textContent=first.toLocaleDateString(undefined,{month:'long',year:'numeric'}).toUpperCase();const today=isoDate(new Date());let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=isoDate(d),dayTasks=tasks.filter(t=>planner.schedule[t.id]===iso),outside=d.getMonth()!==month-1;html+=`<div class="calendar-day ${outside?'outside':''} ${iso===today?'today':''}" data-date="${iso}"><div class="day-number"><span>${d.getDate()}</span>${iso===today?'<em>TODAY</em>':''}</div><div class="day-tasks">${dayTasks.map(t=>taskCard(t,true)).join('')}</div></div>`}$('calendarGrid').innerHTML=html}
function bindTaskInteractions(){document.querySelectorAll('.planner-task').forEach(card=>card.ondragstart=e=>{e.dataTransfer.setData('text/plain',card.dataset.taskId);e.dataTransfer.effectAllowed='move'});document.querySelectorAll('.calendar-day').forEach(day=>{day.ondragover=e=>{e.preventDefault();day.classList.add('drag-over')};day.ondragleave=()=>day.classList.remove('drag-over');day.ondrop=e=>{e.preventDefault();day.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain');if(id){planner.schedule[id]=day.dataset.date;savePlanner();renderTracker()}}});$('taskBacklog').ondragover=e=>e.preventDefault();$('taskBacklog').ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(id){delete planner.schedule[id];savePlanner();renderTracker()}};document.querySelectorAll('[data-complete-id]').forEach(b=>b.onclick=e=>{e.stopPropagation();const t=planner.customTasks.find(x=>x.id===b.dataset.completeId);if(t){t.complete=!t.complete;savePlanner();renderTracker()}})}
function shiftMonth(delta){const [y,m]=planner.month.split('-').map(Number),d=new Date(y,m-1+delta,1);planner.month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;savePlanner();renderTracker()}
$('prevMonth').onclick=()=>shiftMonth(-1);$('nextMonth').onclick=()=>shiftMonth(1);$('todayMonth').onclick=()=>{planner.month=new Date().toISOString().slice(0,7);savePlanner();renderTracker()};
function showCustomForm(){$('customTaskForm').hidden=false;$('customTaskTitle').focus();$('customTaskForm').scrollIntoView({behavior:'smooth',block:'center'})}$('inlineNewTask').onclick=showCustomForm;$('cancelCustomTask').onclick=()=>$('customTaskForm').hidden=true;$('customTaskForm').onsubmit=e=>{e.preventDefault();planner.customTasks.push({id:`custom:${crypto.randomUUID()}`,title:$('customTaskTitle').value.trim(),type:$('customTaskType').value,source:$('customTaskType').value,days:+$('customTaskDays').value||1,complete:false});savePlanner();e.currentTarget.reset();$('customTaskDays').value=1;e.currentTarget.hidden=true;renderTracker();toast('TASK ADDED TO BACKLOG')};

const originalSetTab=setTab,originalCreate=$('createBtn').onclick;setTab=function(tab){$('trackerView').hidden=tab!=='tracker';$('parasytesView').hidden=tab!=='parasytes';$('createBtn').hidden=tab==='parasytes';if(tab==='tracker'||tab==='parasytes'){state.tab=tab;document.querySelectorAll('.nav[data-tab]').forEach(n=>n.classList.toggle('active',n.dataset.tab===tab));$('charactersView').hidden=true;$('modifiersView').hidden=true;$('npcsView').hidden=true;if(tab==='tracker'){$('pageTitle').textContent='Production Tracker';$('breadcrumb').textContent='CALENDAR';$('pageSubtitle').textContent='Schedule incomplete work by day and watch completion sync from every database.';$('createBtn').textContent='＋ NEW TASK';$('createBtn').onclick=showCustomForm;renderTracker()}else{$('pageTitle').textContent='Parasytes';$('breadcrumb').textContent='UPGRADE FAMILIES';$('pageSubtitle').textContent='Track every Parasyte evolution level and its 500 × 500 game asset.';renderParasytes()}}else{$('createBtn').hidden=false;$('createBtn').onclick=originalCreate;originalSetTab(tab)}};
document.querySelector('.nav[data-tab="tracker"]').onclick=()=>setTab('tracker');document.querySelector('.nav[data-tab="parasytes"]').onclick=()=>setTab('parasytes');
function decorateNpcCards(){document.querySelectorAll('.npc-card').forEach(card=>{const n=state.npcs.find(x=>x.id===card.dataset.id),visual=card.querySelector('.npc-visual');if(visual&&!visual.querySelector('.npc-zone-badge'))visual.insertAdjacentHTML('beforeend',`<span class="npc-zone-badge">${escapeHtml((n?.zone||'Graveyard').toUpperCase())}</span>`)})}
function decorateVariantNodes(){const grid=$('characterGrid');if(!grid)return;grid.querySelectorAll('.variant-node-card').forEach(n=>n.remove());let added=0;state.characters.forEach(c=>{if(!c.showVariantsAsNodes)return;const status=completionFor(c),query=`${c.gameName} ${c.fileName} ${(c.variants||[]).map(v=>v.name).join(' ')}`.toLowerCase();if(!query.includes(state.charQuery)||(state.charZone!=='All'&&(c.zone||'Graveyard')!==state.charZone)||(state.completion!=='All'||false)&&((state.completion==='Complete')!==status.complete))return;(c.variants||[]).filter(v=>v.name||v.gif).forEach((v,index)=>{grid.insertAdjacentHTML('beforeend',`<article class="char-card variant-node-card" data-parent-id="${c.id}" data-variant-index="${index}"><div class="char-visual">${v.gif?`<img src="${v.gif}" alt="${escapeHtml(c.gameName||c.fileName)} variant">`:`<span class="initial">${escapeHtml((c.gameName||c.fileName||'?')[0])}</span>`}<span class="asset-spec">VARIANT // 540×960</span><span class="variant-node-badge">VARIANT</span><span class="zone-badge">${escapeHtml((c.zone||'Graveyard').toUpperCase())}</span></div><div class="char-info"><h3>${escapeHtml(c.gameName||c.fileName||'UNNAMED')}</h3><span class="code">${escapeHtml(v.name||`VARIANT_${index+1}`)}</span><div class="chips"><span class="chip">VARIANT NODE</span><span class="chip">PARENT: ${escapeHtml(c.fileName||'—')}</span></div></div></article>`);added++})});grid.querySelectorAll('.variant-node-card').forEach(card=>card.onclick=()=>openCharacter(card.dataset.parentId));if(added){grid.hidden=false;$('characterEmpty').hidden=true}}
function syncVariantDisplayFlag(){state.characters.forEach(c=>c.showVariantsAsNodes=!!rosterView.showVariants)}
function groupVariantNodes(){state.characters.forEach(c=>{const parent=document.querySelector(`.char-card[data-id="${c.id}"]`),variants=[...document.querySelectorAll(`.variant-node-card[data-parent-id="${c.id}"]`)];if(parent)variants.reverse().forEach(node=>parent.insertAdjacentElement('afterend',node))})}
function decorateCharacterCards(){document.querySelectorAll('.char-card').forEach(card=>{const c=state.characters.find(x=>x.id===(card.dataset.id||card.dataset.parentId)),visual=card.querySelector('.char-visual'),info=card.querySelector('.char-info'),status=visual?.querySelector('.status-badge');visual?.querySelector('.asset-spec')?.remove();if(status&&info){status.classList.add('centered-status');info.insertAdjacentElement('afterbegin',status)}if(rosterView.showSpawns&&!card.classList.contains('variant-node-card')&&c?.petImage&&visual){let img=visual.querySelector(':scope > img');if(!img){img=document.createElement('img');visual.prepend(img);visual.querySelector('.initial')?.remove()}img.src=c.petImage;img.alt=`${c.gameName||c.fileName} Spawn`;visual.querySelector('.pet-chip')?.remove();card.classList.add('spawn-view-card')}})}
function clearCharacterImageOverlays(){document.querySelectorAll('.char-card').forEach(card=>{const visual=card.querySelector('.char-visual'),chips=card.querySelector('.chips'),zone=visual?.querySelector('.zone-badge'),spawn=visual?.querySelector('.pet-chip');if(zone&&chips){chips.insertAdjacentHTML('beforeend',`<span class="chip">${escapeHtml(zone.textContent)}</span>`);zone.remove()}if(spawn&&chips){chips.insertAdjacentHTML('beforeend','<span class="chip">SPAWN READY</span>');spawn.remove()}})}
const originalRender=render;render=function(){syncVariantDisplayFlag();originalRender();decorateNpcCards();decorateVariantNodes();groupVariantNodes();decorateCharacterCards();clearCharacterImageOverlays();if(!$('trackerView').hidden)renderTracker()};syncVariantDisplayFlag();decorateNpcCards();decorateVariantNodes();groupVariantNodes();decorateCharacterCards();clearCharacterImageOverlays();renderTracker();
function restartRosterGifs(){const objectUrls=[],images=[...document.querySelectorAll('#characterGrid .char-visual > img')].map(img=>({img,src:img.getAttribute('src')})).filter(x=>x.src).map(item=>{if(item.src.startsWith('data:')){const [header,payload]=item.src.split(','),mime=header.match(/data:([^;]+)/)?.[1]||'image/gif',binary=atob(payload),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);item.fresh=URL.createObjectURL(new Blob([bytes],{type:mime}));objectUrls.push(item.fresh)}return item});images.forEach(({img})=>img.removeAttribute('src'));requestAnimationFrame(()=>requestAnimationFrame(()=>{const stamp=Date.now();images.forEach(({img,src,fresh})=>{img.src=fresh||(src.includes('?')?`${src}&sync=${stamp}`:`${src}?sync=${stamp}`)});setTimeout(()=>objectUrls.forEach(URL.revokeObjectURL),300000)}))}
$('globalVariantNodes').onchange=e=>{rosterView.showVariants=e.target.checked;localStorage.setItem(ROSTER_VIEW_KEY,JSON.stringify(rosterView));render();restartRosterGifs()};$('globalSpawnView').onchange=e=>{rosterView.showSpawns=e.target.checked;localStorage.setItem(ROSTER_VIEW_KEY,JSON.stringify(rosterView));render()};
setTimeout(()=>{let changed=false;state.npcs.forEach(n=>{if(!n.zone){n.zone='Graveyard';changed=true}if(n.forceComplete){n.production=Object.fromEntries(productionTasks.map(t=>[t,true]));n.unity=Object.fromEntries(unityTasks.map(t=>[t,true]));changed=true}});if(changed){save();render()}},1200);
